### YamlMime:ManagedReference
items:
- uid: DynamoForRevitUtils.Entities.WallElevation
  commentId: T:DynamoForRevitUtils.Entities.WallElevation
  id: WallElevation
  parent: DynamoForRevitUtils.Entities
  children:
  - DynamoForRevitUtils.Entities.WallElevation.#ctor(System.String,Autodesk.Revit.DB.Wall,Autodesk.Revit.DB.ViewFamilyType,System.Double,System.Boolean,DynamoForRevitUtils.Entities.CropRegionOffsetSettings)
  - DynamoForRevitUtils.Entities.WallElevation.CreateElevationView(Autodesk.Revit.DB.ViewPlan,System.Int32,Autodesk.Revit.DB.RevitLinkInstance,System.Boolean)
  - DynamoForRevitUtils.Entities.WallElevation.CropRegionOffsetSettings
  - DynamoForRevitUtils.Entities.WallElevation.Elevation
  - DynamoForRevitUtils.Entities.WallElevation.ElevationMarker
  - DynamoForRevitUtils.Entities.WallElevation.ElevationPoint
  - DynamoForRevitUtils.Entities.WallElevation.FarClipOffset
  - DynamoForRevitUtils.Entities.WallElevation.Flipped
  - DynamoForRevitUtils.Entities.WallElevation.Name
  - DynamoForRevitUtils.Entities.WallElevation.OffsetFromWall
  - DynamoForRevitUtils.Entities.WallElevation.Scale
  - DynamoForRevitUtils.Entities.WallElevation.ToString
  - DynamoForRevitUtils.Entities.WallElevation.ViewFamilyType
  - DynamoForRevitUtils.Entities.WallElevation.Wall
  - DynamoForRevitUtils.Entities.WallElevation.WallBaseLine
  - DynamoForRevitUtils.Entities.WallElevation.WallCenterPoint
  - DynamoForRevitUtils.Entities.WallElevation.WallLocationCurve
  - DynamoForRevitUtils.Entities.WallElevation.WallMidPoint
  - DynamoForRevitUtils.Entities.WallElevation.WallNormal
  langs:
  - csharp
  - vb
  name: WallElevation
  nameWithType: WallElevation
  fullName: DynamoForRevitUtils.Entities.WallElevation
  type: Class
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Class containing data to create a Wall Elevation
  example: []
  syntax:
    content: >-
      [IsVisibleInDynamoLibrary(false)]

      public class WallElevation
    content.vb: >-
      <IsVisibleInDynamoLibrary(False)>

      Public Class WallElevation
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  extensionMethods:
  - System.Object.DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1
  attributes:
  - type: Autodesk.DesignScript.Runtime.IsVisibleInDynamoLibraryAttribute
    ctor: Autodesk.DesignScript.Runtime.IsVisibleInDynamoLibraryAttribute.#ctor(System.Boolean)
    arguments:
    - type: System.Boolean
      value: false
- uid: DynamoForRevitUtils.Entities.WallElevation.#ctor(System.String,Autodesk.Revit.DB.Wall,Autodesk.Revit.DB.ViewFamilyType,System.Double,System.Boolean,DynamoForRevitUtils.Entities.CropRegionOffsetSettings)
  commentId: M:DynamoForRevitUtils.Entities.WallElevation.#ctor(System.String,Autodesk.Revit.DB.Wall,Autodesk.Revit.DB.ViewFamilyType,System.Double,System.Boolean,DynamoForRevitUtils.Entities.CropRegionOffsetSettings)
  id: '#ctor(System.String,Autodesk.Revit.DB.Wall,Autodesk.Revit.DB.ViewFamilyType,System.Double,System.Boolean,DynamoForRevitUtils.Entities.CropRegionOffsetSettings)'
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: WallElevation(string, Wall, ViewFamilyType, double, bool, CropRegionOffsetSettings?)
  nameWithType: WallElevation.WallElevation(string, Wall, ViewFamilyType, double, bool, CropRegionOffsetSettings?)
  fullName: DynamoForRevitUtils.Entities.WallElevation.WallElevation(string, Autodesk.Revit.DB.Wall, Autodesk.Revit.DB.ViewFamilyType, double, bool, DynamoForRevitUtils.Entities.CropRegionOffsetSettings?)
  type: Constructor
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Construct object that holds data to create Wall Elevation
  example: []
  syntax:
    content: public WallElevation(string name, Wall wall, ViewFamilyType viewFamilyType, double elevationOffset = 1, bool flip = false, CropRegionOffsetSettings? cropRegionOffsetSettings = null)
    parameters:
    - id: name
      type: System.String
      description: Elevation View Name. Must be unique
    - id: wall
      type: Autodesk.Revit.DB.Wall
      description: Revit Wall to create elevation
    - id: viewFamilyType
      type: Autodesk.Revit.DB.ViewFamilyType
      description: The Elevation Type
    - id: elevationOffset
      type: System.Double
      description: Distance of Elevation Marker from Wall
    - id: flip
      type: System.Boolean
      description: Whether elevation must be flipped or not
    - id: cropRegionOffsetSettings
      type: DynamoForRevitUtils.Entities.CropRegionOffsetSettings
      description: >-
        Crop Region Shape offset settings.

        The default Crop Region Shape is defined by planar Wall boundary curves.

        Leave null to use default Crop Region Shape without offset.
    content.vb: Public Sub New(name As String, wall As Wall, viewFamilyType As ViewFamilyType, elevationOffset As Double = 1, flip As Boolean = False, cropRegionOffsetSettings As CropRegionOffsetSettings = Nothing)
  overload: DynamoForRevitUtils.Entities.WallElevation.#ctor*
  nameWithType.vb: WallElevation.New(String, Wall, ViewFamilyType, Double, Boolean, CropRegionOffsetSettings)
  fullName.vb: DynamoForRevitUtils.Entities.WallElevation.New(String, Autodesk.Revit.DB.Wall, Autodesk.Revit.DB.ViewFamilyType, Double, Boolean, DynamoForRevitUtils.Entities.CropRegionOffsetSettings)
  name.vb: New(String, Wall, ViewFamilyType, Double, Boolean, CropRegionOffsetSettings)
- uid: DynamoForRevitUtils.Entities.WallElevation.CreateElevationView(Autodesk.Revit.DB.ViewPlan,System.Int32,Autodesk.Revit.DB.RevitLinkInstance,System.Boolean)
  commentId: M:DynamoForRevitUtils.Entities.WallElevation.CreateElevationView(Autodesk.Revit.DB.ViewPlan,System.Int32,Autodesk.Revit.DB.RevitLinkInstance,System.Boolean)
  id: CreateElevationView(Autodesk.Revit.DB.ViewPlan,System.Int32,Autodesk.Revit.DB.RevitLinkInstance,System.Boolean)
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: CreateElevationView(ViewPlan, int, RevitLinkInstance?, bool)
  nameWithType: WallElevation.CreateElevationView(ViewPlan, int, RevitLinkInstance?, bool)
  fullName: DynamoForRevitUtils.Entities.WallElevation.CreateElevationView(Autodesk.Revit.DB.ViewPlan, int, Autodesk.Revit.DB.RevitLinkInstance?, bool)
  type: Method
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Creates a new Elevation View aligned to the Wall.
  example: []
  syntax:
    content: public void CreateElevationView(ViewPlan viewPlan, int scale = 100, RevitLinkInstance? linkInstance = null, bool attachToGrid = false)
    parameters:
    - id: viewPlan
      type: Autodesk.Revit.DB.ViewPlan
      description: Plan View to create elevation
    - id: scale
      type: System.Int32
      description: View scale
    - id: linkInstance
      type: Autodesk.Revit.DB.RevitLinkInstance
      description: Revit Link Instance which Wall belongs
    - id: attachToGrid
      type: System.Boolean
      description: Set true if you want to attach this Elevation to the Wall nearest parallel Grid.
    content.vb: Public Sub CreateElevationView(viewPlan As ViewPlan, scale As Integer = 100, linkInstance As RevitLinkInstance = Nothing, attachToGrid As Boolean = False)
  overload: DynamoForRevitUtils.Entities.WallElevation.CreateElevationView*
  nameWithType.vb: WallElevation.CreateElevationView(ViewPlan, Integer, RevitLinkInstance, Boolean)
  fullName.vb: DynamoForRevitUtils.Entities.WallElevation.CreateElevationView(Autodesk.Revit.DB.ViewPlan, Integer, Autodesk.Revit.DB.RevitLinkInstance, Boolean)
  name.vb: CreateElevationView(ViewPlan, Integer, RevitLinkInstance, Boolean)
- uid: DynamoForRevitUtils.Entities.WallElevation.ToString
  commentId: M:DynamoForRevitUtils.Entities.WallElevation.ToString
  id: ToString
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: ToString()
  nameWithType: WallElevation.ToString()
  fullName: DynamoForRevitUtils.Entities.WallElevation.ToString()
  type: Method
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  example: []
  syntax:
    content: public override string ToString()
    return:
      type: System.String
    content.vb: Public Overrides Function ToString() As String
  overridden: System.Object.ToString
  overload: DynamoForRevitUtils.Entities.WallElevation.ToString*
- uid: DynamoForRevitUtils.Entities.WallElevation.WallNormal
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.WallNormal
  id: WallNormal
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: WallNormal
  nameWithType: WallElevation.WallNormal
  fullName: DynamoForRevitUtils.Entities.WallElevation.WallNormal
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Wall normal vector
  example: []
  syntax:
    content: public Vector WallNormal { get; }
    parameters: []
    return:
      type: Autodesk.DesignScript.Geometry.Vector
    content.vb: Public ReadOnly Property WallNormal As Vector
  overload: DynamoForRevitUtils.Entities.WallElevation.WallNormal*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: Throws if assigned value was null
- uid: DynamoForRevitUtils.Entities.WallElevation.WallBaseLine
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.WallBaseLine
  id: WallBaseLine
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: WallBaseLine
  nameWithType: WallElevation.WallBaseLine
  fullName: DynamoForRevitUtils.Entities.WallElevation.WallBaseLine
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Line created by Location Curve of Wall, by getting its StartPoint and EndPoint
  example: []
  syntax:
    content: public Line WallBaseLine { get; }
    parameters: []
    return:
      type: Autodesk.DesignScript.Geometry.Line
    content.vb: Public ReadOnly Property WallBaseLine As Line
  overload: DynamoForRevitUtils.Entities.WallElevation.WallBaseLine*
- uid: DynamoForRevitUtils.Entities.WallElevation.WallLocationCurve
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.WallLocationCurve
  id: WallLocationCurve
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: WallLocationCurve
  nameWithType: WallElevation.WallLocationCurve
  fullName: DynamoForRevitUtils.Entities.WallElevation.WallLocationCurve
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Wall location curve as returned by Revit API
  example: []
  syntax:
    content: public Curve WallLocationCurve { get; }
    parameters: []
    return:
      type: Autodesk.DesignScript.Geometry.Curve
    content.vb: Public ReadOnly Property WallLocationCurve As Curve
  overload: DynamoForRevitUtils.Entities.WallElevation.WallLocationCurve*
- uid: DynamoForRevitUtils.Entities.WallElevation.WallMidPoint
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.WallMidPoint
  id: WallMidPoint
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: WallMidPoint
  nameWithType: WallElevation.WallMidPoint
  fullName: DynamoForRevitUtils.Entities.WallElevation.WallMidPoint
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Wall location curve mid point
  example: []
  syntax:
    content: public Point WallMidPoint { get; }
    parameters: []
    return:
      type: Autodesk.DesignScript.Geometry.Point
    content.vb: Public ReadOnly Property WallMidPoint As Point
  overload: DynamoForRevitUtils.Entities.WallElevation.WallMidPoint*
- uid: DynamoForRevitUtils.Entities.WallElevation.WallCenterPoint
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.WallCenterPoint
  id: WallCenterPoint
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: WallCenterPoint
  nameWithType: WallElevation.WallCenterPoint
  fullName: DynamoForRevitUtils.Entities.WallElevation.WallCenterPoint
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Wall base line mid point
  example: []
  syntax:
    content: public Point WallCenterPoint { get; }
    parameters: []
    return:
      type: Autodesk.DesignScript.Geometry.Point
    content.vb: Public ReadOnly Property WallCenterPoint As Point
  overload: DynamoForRevitUtils.Entities.WallElevation.WallCenterPoint*
- uid: DynamoForRevitUtils.Entities.WallElevation.ElevationPoint
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.ElevationPoint
  id: ElevationPoint
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: ElevationPoint
  nameWithType: WallElevation.ElevationPoint
  fullName: DynamoForRevitUtils.Entities.WallElevation.ElevationPoint
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Elevation Marker Location Point
  example: []
  syntax:
    content: public Point ElevationPoint { get; }
    parameters: []
    return:
      type: Autodesk.DesignScript.Geometry.Point
    content.vb: Public ReadOnly Property ElevationPoint As Point
  overload: DynamoForRevitUtils.Entities.WallElevation.ElevationPoint*
- uid: DynamoForRevitUtils.Entities.WallElevation.FarClipOffset
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.FarClipOffset
  id: FarClipOffset
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: FarClipOffset
  nameWithType: WallElevation.FarClipOffset
  fullName: DynamoForRevitUtils.Entities.WallElevation.FarClipOffset
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Elevation Far Clip Offset calculated from Wall Width and Elevation Point
  example: []
  syntax:
    content: public double FarClipOffset { get; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public ReadOnly Property FarClipOffset As Double
  overload: DynamoForRevitUtils.Entities.WallElevation.FarClipOffset*
- uid: DynamoForRevitUtils.Entities.WallElevation.Name
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.Name
  id: Name
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: WallElevation.Name
  fullName: DynamoForRevitUtils.Entities.WallElevation.Name
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Elevation View Name
  example: []
  syntax:
    content: public string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Name As String
  overload: DynamoForRevitUtils.Entities.WallElevation.Name*
- uid: DynamoForRevitUtils.Entities.WallElevation.Wall
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.Wall
  id: Wall
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: Wall
  nameWithType: WallElevation.Wall
  fullName: DynamoForRevitUtils.Entities.WallElevation.Wall
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Wall associated with Elevation
  example: []
  syntax:
    content: public Wall Wall { get; }
    parameters: []
    return:
      type: Autodesk.Revit.DB.Wall
    content.vb: Public ReadOnly Property Wall As Wall
  overload: DynamoForRevitUtils.Entities.WallElevation.Wall*
- uid: DynamoForRevitUtils.Entities.WallElevation.ViewFamilyType
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.ViewFamilyType
  id: ViewFamilyType
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: ViewFamilyType
  nameWithType: WallElevation.ViewFamilyType
  fullName: DynamoForRevitUtils.Entities.WallElevation.ViewFamilyType
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Elevation View Family Type
  example: []
  syntax:
    content: public ViewFamilyType ViewFamilyType { get; }
    parameters: []
    return:
      type: Autodesk.Revit.DB.ViewFamilyType
    content.vb: Public ReadOnly Property ViewFamilyType As ViewFamilyType
  overload: DynamoForRevitUtils.Entities.WallElevation.ViewFamilyType*
- uid: DynamoForRevitUtils.Entities.WallElevation.Scale
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.Scale
  id: Scale
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: Scale
  nameWithType: WallElevation.Scale
  fullName: DynamoForRevitUtils.Entities.WallElevation.Scale
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Elevation View Scale
  example: []
  syntax:
    content: public int Scale { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property Scale As Integer
  overload: DynamoForRevitUtils.Entities.WallElevation.Scale*
- uid: DynamoForRevitUtils.Entities.WallElevation.OffsetFromWall
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.OffsetFromWall
  id: OffsetFromWall
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: OffsetFromWall
  nameWithType: WallElevation.OffsetFromWall
  fullName: DynamoForRevitUtils.Entities.WallElevation.OffsetFromWall
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Elevation Symbol offset from Wall
  example: []
  syntax:
    content: public double OffsetFromWall { get; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public ReadOnly Property OffsetFromWall As Double
  overload: DynamoForRevitUtils.Entities.WallElevation.OffsetFromWall*
- uid: DynamoForRevitUtils.Entities.WallElevation.CropRegionOffsetSettings
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.CropRegionOffsetSettings
  id: CropRegionOffsetSettings
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: CropRegionOffsetSettings
  nameWithType: WallElevation.CropRegionOffsetSettings
  fullName: DynamoForRevitUtils.Entities.WallElevation.CropRegionOffsetSettings
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Crop Region Shape offset from Wall
  example: []
  syntax:
    content: public CropRegionOffsetSettings CropRegionOffsetSettings { get; }
    parameters: []
    return:
      type: DynamoForRevitUtils.Entities.CropRegionOffsetSettings
    content.vb: Public ReadOnly Property CropRegionOffsetSettings As CropRegionOffsetSettings
  overload: DynamoForRevitUtils.Entities.WallElevation.CropRegionOffsetSettings*
- uid: DynamoForRevitUtils.Entities.WallElevation.Flipped
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.Flipped
  id: Flipped
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: Flipped
  nameWithType: WallElevation.Flipped
  fullName: DynamoForRevitUtils.Entities.WallElevation.Flipped
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Whether Elevation is flipped or not
  example: []
  syntax:
    content: public bool Flipped { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public ReadOnly Property Flipped As Boolean
  overload: DynamoForRevitUtils.Entities.WallElevation.Flipped*
- uid: DynamoForRevitUtils.Entities.WallElevation.Elevation
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.Elevation
  id: Elevation
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: Elevation
  nameWithType: WallElevation.Elevation
  fullName: DynamoForRevitUtils.Entities.WallElevation.Elevation
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Elevation View Section
  example: []
  syntax:
    content: public ViewSection Elevation { get; }
    parameters: []
    return:
      type: Autodesk.Revit.DB.ViewSection
    content.vb: Public ReadOnly Property Elevation As ViewSection
  overload: DynamoForRevitUtils.Entities.WallElevation.Elevation*
- uid: DynamoForRevitUtils.Entities.WallElevation.ElevationMarker
  commentId: P:DynamoForRevitUtils.Entities.WallElevation.ElevationMarker
  id: ElevationMarker
  parent: DynamoForRevitUtils.Entities.WallElevation
  langs:
  - csharp
  - vb
  name: ElevationMarker
  nameWithType: WallElevation.ElevationMarker
  fullName: DynamoForRevitUtils.Entities.WallElevation.ElevationMarker
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Elevation View Elevation Marker
  example: []
  syntax:
    content: public ElevationMarker ElevationMarker { get; }
    parameters: []
    return:
      type: Autodesk.Revit.DB.ElevationMarker
    content.vb: Public ReadOnly Property ElevationMarker As ElevationMarker
  overload: DynamoForRevitUtils.Entities.WallElevation.ElevationMarker*
references:
- uid: DynamoForRevitUtils.Entities
  commentId: N:DynamoForRevitUtils.Entities
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Entities
  nameWithType: DynamoForRevitUtils.Entities
  fullName: DynamoForRevitUtils.Entities
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Entities
    name: Entities
    isExternal: true
    href: DynamoForRevitUtils.Entities.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Entities
    name: Entities
    isExternal: true
    href: DynamoForRevitUtils.Entities.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1
  commentId: M:DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  parent: DynamoForRevitUtils.Services.GenericServices.ObjectServices
  definition: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  name: TryCast<T>(object)
  nameWithType: ObjectServices.TryCast<T>(object)
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast<T>(object)
  nameWithType.vb: ObjectServices.TryCast(Of T)(Object)
  fullName.vb: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast(Of T)(Object)
  name.vb: TryCast(Of T)(Object)
  spec.csharp:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  commentId: M:DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  isExternal: true
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  name: TryCast<T>(object)
  nameWithType: ObjectServices.TryCast<T>(object)
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast<T>(object)
  nameWithType.vb: ObjectServices.TryCast(Of T)(Object)
  fullName.vb: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast(Of T)(Object)
  name.vb: TryCast(Of T)(Object)
  spec.csharp:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices
  commentId: T:DynamoForRevitUtils.Services.GenericServices.ObjectServices
  parent: DynamoForRevitUtils.Services.GenericServices
  isExternal: true
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html
  name: ObjectServices
  nameWithType: ObjectServices
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices
- uid: DynamoForRevitUtils.Services.GenericServices
  commentId: N:DynamoForRevitUtils.Services.GenericServices
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Services.GenericServices
  nameWithType: DynamoForRevitUtils.Services.GenericServices
  fullName: DynamoForRevitUtils.Services.GenericServices
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.GenericServices
    name: GenericServices
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.GenericServices
    name: GenericServices
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.html
- uid: DynamoForRevitUtils.Entities.WallElevation.#ctor*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.#ctor
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation__ctor_System_String_Autodesk_Revit_DB_Wall_Autodesk_Revit_DB_ViewFamilyType_System_Double_System_Boolean_DynamoForRevitUtils_Entities_CropRegionOffsetSettings_
  name: WallElevation
  nameWithType: WallElevation.WallElevation
  fullName: DynamoForRevitUtils.Entities.WallElevation.WallElevation
  nameWithType.vb: WallElevation.New
  fullName.vb: DynamoForRevitUtils.Entities.WallElevation.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Autodesk.Revit.DB.Wall
  commentId: T:Autodesk.Revit.DB.Wall
  parent: Autodesk.Revit.DB
  isExternal: true
  name: Wall
  nameWithType: Wall
  fullName: Autodesk.Revit.DB.Wall
- uid: Autodesk.Revit.DB.ViewFamilyType
  commentId: T:Autodesk.Revit.DB.ViewFamilyType
  parent: Autodesk.Revit.DB
  isExternal: true
  name: ViewFamilyType
  nameWithType: ViewFamilyType
  fullName: Autodesk.Revit.DB.ViewFamilyType
- uid: System.Double
  commentId: T:System.Double
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.double
  name: double
  nameWithType: double
  fullName: double
  nameWithType.vb: Double
  fullName.vb: Double
  name.vb: Double
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: DynamoForRevitUtils.Entities.CropRegionOffsetSettings
  commentId: T:DynamoForRevitUtils.Entities.CropRegionOffsetSettings
  parent: DynamoForRevitUtils.Entities
  isExternal: true
  href: DynamoForRevitUtils.Entities.CropRegionOffsetSettings.html
  name: CropRegionOffsetSettings
  nameWithType: CropRegionOffsetSettings
  fullName: DynamoForRevitUtils.Entities.CropRegionOffsetSettings
- uid: Autodesk.Revit.DB
  commentId: N:Autodesk.Revit.DB
  isExternal: true
  name: Autodesk.Revit.DB
  nameWithType: Autodesk.Revit.DB
  fullName: Autodesk.Revit.DB
  spec.csharp:
  - uid: Autodesk
    name: Autodesk
    isExternal: true
  - name: .
  - uid: Autodesk.Revit
    name: Revit
    isExternal: true
  - name: .
  - uid: Autodesk.Revit.DB
    name: DB
    isExternal: true
  spec.vb:
  - uid: Autodesk
    name: Autodesk
    isExternal: true
  - name: .
  - uid: Autodesk.Revit
    name: Revit
    isExternal: true
  - name: .
  - uid: Autodesk.Revit.DB
    name: DB
    isExternal: true
- uid: DynamoForRevitUtils.Entities.WallElevation.CreateElevationView*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.CreateElevationView
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_CreateElevationView_Autodesk_Revit_DB_ViewPlan_System_Int32_Autodesk_Revit_DB_RevitLinkInstance_System_Boolean_
  name: CreateElevationView
  nameWithType: WallElevation.CreateElevationView
  fullName: DynamoForRevitUtils.Entities.WallElevation.CreateElevationView
- uid: Autodesk.Revit.DB.ViewPlan
  commentId: T:Autodesk.Revit.DB.ViewPlan
  parent: Autodesk.Revit.DB
  isExternal: true
  name: ViewPlan
  nameWithType: ViewPlan
  fullName: Autodesk.Revit.DB.ViewPlan
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Autodesk.Revit.DB.RevitLinkInstance
  commentId: T:Autodesk.Revit.DB.RevitLinkInstance
  parent: Autodesk.Revit.DB
  isExternal: true
  name: RevitLinkInstance
  nameWithType: RevitLinkInstance
  fullName: Autodesk.Revit.DB.RevitLinkInstance
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: DynamoForRevitUtils.Entities.WallElevation.ToString*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.ToString
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_ToString
  name: ToString
  nameWithType: WallElevation.ToString
  fullName: DynamoForRevitUtils.Entities.WallElevation.ToString
- uid: System.ArgumentNullException
  commentId: T:System.ArgumentNullException
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.argumentnullexception
  name: ArgumentNullException
  nameWithType: ArgumentNullException
  fullName: System.ArgumentNullException
- uid: DynamoForRevitUtils.Entities.WallElevation.WallNormal*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.WallNormal
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_WallNormal
  name: WallNormal
  nameWithType: WallElevation.WallNormal
  fullName: DynamoForRevitUtils.Entities.WallElevation.WallNormal
- uid: Autodesk.DesignScript.Geometry.Vector
  commentId: T:Autodesk.DesignScript.Geometry.Vector
  parent: Autodesk.DesignScript.Geometry
  isExternal: true
  name: Vector
  nameWithType: Vector
  fullName: Autodesk.DesignScript.Geometry.Vector
- uid: Autodesk.DesignScript.Geometry
  commentId: N:Autodesk.DesignScript.Geometry
  isExternal: true
  name: Autodesk.DesignScript.Geometry
  nameWithType: Autodesk.DesignScript.Geometry
  fullName: Autodesk.DesignScript.Geometry
  spec.csharp:
  - uid: Autodesk
    name: Autodesk
    isExternal: true
  - name: .
  - uid: Autodesk.DesignScript
    name: DesignScript
    isExternal: true
  - name: .
  - uid: Autodesk.DesignScript.Geometry
    name: Geometry
    isExternal: true
  spec.vb:
  - uid: Autodesk
    name: Autodesk
    isExternal: true
  - name: .
  - uid: Autodesk.DesignScript
    name: DesignScript
    isExternal: true
  - name: .
  - uid: Autodesk.DesignScript.Geometry
    name: Geometry
    isExternal: true
- uid: DynamoForRevitUtils.Entities.WallElevation.WallBaseLine*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.WallBaseLine
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_WallBaseLine
  name: WallBaseLine
  nameWithType: WallElevation.WallBaseLine
  fullName: DynamoForRevitUtils.Entities.WallElevation.WallBaseLine
- uid: Autodesk.DesignScript.Geometry.Line
  commentId: T:Autodesk.DesignScript.Geometry.Line
  parent: Autodesk.DesignScript.Geometry
  isExternal: true
  name: Line
  nameWithType: Line
  fullName: Autodesk.DesignScript.Geometry.Line
- uid: DynamoForRevitUtils.Entities.WallElevation.WallLocationCurve*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.WallLocationCurve
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_WallLocationCurve
  name: WallLocationCurve
  nameWithType: WallElevation.WallLocationCurve
  fullName: DynamoForRevitUtils.Entities.WallElevation.WallLocationCurve
- uid: Autodesk.DesignScript.Geometry.Curve
  commentId: T:Autodesk.DesignScript.Geometry.Curve
  parent: Autodesk.DesignScript.Geometry
  isExternal: true
  name: Curve
  nameWithType: Curve
  fullName: Autodesk.DesignScript.Geometry.Curve
- uid: DynamoForRevitUtils.Entities.WallElevation.WallMidPoint*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.WallMidPoint
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_WallMidPoint
  name: WallMidPoint
  nameWithType: WallElevation.WallMidPoint
  fullName: DynamoForRevitUtils.Entities.WallElevation.WallMidPoint
- uid: Autodesk.DesignScript.Geometry.Point
  commentId: T:Autodesk.DesignScript.Geometry.Point
  parent: Autodesk.DesignScript.Geometry
  isExternal: true
  name: Point
  nameWithType: Point
  fullName: Autodesk.DesignScript.Geometry.Point
- uid: DynamoForRevitUtils.Entities.WallElevation.WallCenterPoint*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.WallCenterPoint
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_WallCenterPoint
  name: WallCenterPoint
  nameWithType: WallElevation.WallCenterPoint
  fullName: DynamoForRevitUtils.Entities.WallElevation.WallCenterPoint
- uid: DynamoForRevitUtils.Entities.WallElevation.ElevationPoint*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.ElevationPoint
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_ElevationPoint
  name: ElevationPoint
  nameWithType: WallElevation.ElevationPoint
  fullName: DynamoForRevitUtils.Entities.WallElevation.ElevationPoint
- uid: DynamoForRevitUtils.Entities.WallElevation.FarClipOffset*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.FarClipOffset
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_FarClipOffset
  name: FarClipOffset
  nameWithType: WallElevation.FarClipOffset
  fullName: DynamoForRevitUtils.Entities.WallElevation.FarClipOffset
- uid: DynamoForRevitUtils.Entities.WallElevation.Name*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.Name
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_Name
  name: Name
  nameWithType: WallElevation.Name
  fullName: DynamoForRevitUtils.Entities.WallElevation.Name
- uid: DynamoForRevitUtils.Entities.WallElevation.Wall*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.Wall
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_Wall
  name: Wall
  nameWithType: WallElevation.Wall
  fullName: DynamoForRevitUtils.Entities.WallElevation.Wall
- uid: DynamoForRevitUtils.Entities.WallElevation.ViewFamilyType*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.ViewFamilyType
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_ViewFamilyType
  name: ViewFamilyType
  nameWithType: WallElevation.ViewFamilyType
  fullName: DynamoForRevitUtils.Entities.WallElevation.ViewFamilyType
- uid: DynamoForRevitUtils.Entities.WallElevation.Scale*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.Scale
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_Scale
  name: Scale
  nameWithType: WallElevation.Scale
  fullName: DynamoForRevitUtils.Entities.WallElevation.Scale
- uid: DynamoForRevitUtils.Entities.WallElevation.OffsetFromWall*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.OffsetFromWall
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_OffsetFromWall
  name: OffsetFromWall
  nameWithType: WallElevation.OffsetFromWall
  fullName: DynamoForRevitUtils.Entities.WallElevation.OffsetFromWall
- uid: DynamoForRevitUtils.Entities.WallElevation.CropRegionOffsetSettings*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.CropRegionOffsetSettings
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_CropRegionOffsetSettings
  name: CropRegionOffsetSettings
  nameWithType: WallElevation.CropRegionOffsetSettings
  fullName: DynamoForRevitUtils.Entities.WallElevation.CropRegionOffsetSettings
- uid: DynamoForRevitUtils.Entities.WallElevation.Flipped*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.Flipped
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_Flipped
  name: Flipped
  nameWithType: WallElevation.Flipped
  fullName: DynamoForRevitUtils.Entities.WallElevation.Flipped
- uid: DynamoForRevitUtils.Entities.WallElevation.Elevation*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.Elevation
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_Elevation
  name: Elevation
  nameWithType: WallElevation.Elevation
  fullName: DynamoForRevitUtils.Entities.WallElevation.Elevation
- uid: Autodesk.Revit.DB.ViewSection
  commentId: T:Autodesk.Revit.DB.ViewSection
  parent: Autodesk.Revit.DB
  isExternal: true
  name: ViewSection
  nameWithType: ViewSection
  fullName: Autodesk.Revit.DB.ViewSection
- uid: DynamoForRevitUtils.Entities.WallElevation.ElevationMarker*
  commentId: Overload:DynamoForRevitUtils.Entities.WallElevation.ElevationMarker
  isExternal: true
  href: DynamoForRevitUtils.Entities.WallElevation.html#DynamoForRevitUtils_Entities_WallElevation_ElevationMarker
  name: ElevationMarker
  nameWithType: WallElevation.ElevationMarker
  fullName: DynamoForRevitUtils.Entities.WallElevation.ElevationMarker
- uid: Autodesk.Revit.DB.ElevationMarker
  commentId: T:Autodesk.Revit.DB.ElevationMarker
  parent: Autodesk.Revit.DB
  isExternal: true
  name: ElevationMarker
  nameWithType: ElevationMarker
  fullName: Autodesk.Revit.DB.ElevationMarker
