{
  "DynamoForRevitUtils.Constants": "DynamoForRevitUtils.Constants.yml",
  "DynamoForRevitUtils.Constants.Common": "DynamoForRevitUtils.Constants.Common.yml",
  "DynamoForRevitUtils.Constants.Common.ERROR_TITLE": "DynamoForRevitUtils.Constants.Common.yml",
  "DynamoForRevitUtils.Constants.Common.PACKAGE_NAME": "DynamoForRevitUtils.Constants.Common.yml",
  "DynamoForRevitUtils.Entities": "DynamoForRevitUtils.Entities.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry": "DynamoForRevitUtils.Entities.AbstractGeometry.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractBoundingBox": "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractBoundingBox.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractBoundingBox.#ctor(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractBoundingBox.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractBoundingBox.Visualize(Autodesk.DesignScript.Geometry.Point,System.Double,DSCore.Color,System.Boolean,System.Boolean)": "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractBoundingBox.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractCoordinateSystem": "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractCoordinateSystem.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractCoordinateSystem.#ctor(Autodesk.DesignScript.Geometry.CoordinateSystem)": "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractCoordinateSystem.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractCoordinateSystem.Visualize(Autodesk.DesignScript.Geometry.Point,System.Double,DSCore.Color,System.Boolean,System.Boolean)": "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractCoordinateSystem.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractGeometryBase`1": "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractGeometryBase-1.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractGeometryBase`1.Visualize(Autodesk.DesignScript.Geometry.Point,System.Double,DSCore.Color,System.Boolean,System.Boolean)": "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractGeometryBase-1.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractGeometryBase`1.abstractObject": "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractGeometryBase-1.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractGeometryFactory": "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractGeometryFactory.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractGeometryFactory.GetAbstractGeometryObject(Autodesk.DesignScript.Geometry.DesignScriptEntity)": "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractGeometryFactory.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractVector": "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractVector.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractVector.#ctor(Autodesk.DesignScript.Geometry.Vector)": "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractVector.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractVector.Visualize(Autodesk.DesignScript.Geometry.Point,System.Double,DSCore.Color,System.Boolean,System.Boolean)": "DynamoForRevitUtils.Entities.AbstractGeometry.AbstractVector.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.IAbstractGeometry": "DynamoForRevitUtils.Entities.AbstractGeometry.IAbstractGeometry.yml",
  "DynamoForRevitUtils.Entities.AbstractGeometry.IAbstractGeometry.Visualize(Autodesk.DesignScript.Geometry.Point,System.Double,DSCore.Color,System.Boolean,System.Boolean)": "DynamoForRevitUtils.Entities.AbstractGeometry.IAbstractGeometry.yml",
  "DynamoForRevitUtils.Entities.Axis": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.#ctor(System.String,Autodesk.DesignScript.Geometry.Line)": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.#ctor(System.String,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point)": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.#ctor(System.String,System.Double,System.Double,System.Double,System.Double,System.Double)": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.CoordinateSystem": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.Direction": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.Elevation": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.EndPoint": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.IsPerpendicular": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.IsTranslated": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.Length": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.Line": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.Name": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.Normal": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.Perpendicular(System.Double,System.Nullable{System.Double},System.Boolean,System.Double,System.Double)": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.StartPoint": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.Axis.Translate(Autodesk.DesignScript.Geometry.Vector,System.Double)": "DynamoForRevitUtils.Entities.Axis.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.#ctor(Autodesk.Revit.DB.Architecture.BuildingPad)": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.#ctor(Autodesk.Revit.DB.Ceiling)": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.#ctor(Autodesk.Revit.DB.Floor)": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.#ctor(Autodesk.Revit.DB.HostObjAttributes)": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.#ctor(Autodesk.Revit.DB.RoofBase)": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.#ctor(Autodesk.Revit.DB.Wall)": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.CoreLayers": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.CoreLayersAmount": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.CoreLayersFunctions": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.CoreLayersWidth": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.CoreMaterials": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.CoreMaterialsNames": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.ExteriorLayers": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.ExteriorLayersAmount": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.ExteriorLayersFunctions": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.ExteriorLayersWidth": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.ExteriorMaterials": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.ExteriorMaterialsNames": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.FirstCoreLayerIndex": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.InteriorLayers": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.InteriorLayersAmount": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.InteriorLayersFunctions": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.InteriorLayersWidth": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.InteriorMaterials": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.InteriorMaterialsNames": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.LastCoreLayerIndex": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.Layers": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.Structure": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.ToString": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.TotalWidth": "DynamoForRevitUtils.Entities.CompoundStructureLayersInfo.yml",
  "DynamoForRevitUtils.Entities.CropRegionOffsetSettings": "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.yml",
  "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.Bottom": "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.yml",
  "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.GetAsymmetric(System.Double,System.Double,System.Double,System.Double)": "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.yml",
  "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.GetCropRegionShape(Autodesk.Revit.DB.View,Autodesk.DesignScript.Geometry.Line,Autodesk.DesignScript.Geometry.Line,Autodesk.DesignScript.Geometry.Line,Autodesk.DesignScript.Geometry.Line)": "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.yml",
  "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.GetSymmetric(System.Double)": "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.yml",
  "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.IsSymmetric": "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.yml",
  "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.Left": "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.yml",
  "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.Right": "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.yml",
  "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.ToString": "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.yml",
  "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.Top": "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.yml",
  "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.Unchanged": "DynamoForRevitUtils.Entities.CropRegionOffsetSettings.yml",
  "DynamoForRevitUtils.Entities.EqualityComparers": "DynamoForRevitUtils.Entities.EqualityComparers.yml",
  "DynamoForRevitUtils.Entities.EqualityComparers.ElementComparer": "DynamoForRevitUtils.Entities.EqualityComparers.ElementComparer.yml",
  "DynamoForRevitUtils.Entities.EqualityComparers.ElementComparer.#ctor": "DynamoForRevitUtils.Entities.EqualityComparers.ElementComparer.yml",
  "DynamoForRevitUtils.Entities.EqualityComparers.ElementComparer.Equals(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Entities.EqualityComparers.ElementComparer.yml",
  "DynamoForRevitUtils.Entities.EqualityComparers.ElementComparer.GetHashCode(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Entities.EqualityComparers.ElementComparer.yml",
  "DynamoForRevitUtils.Entities.EqualityComparers.ElementReferenceComparer": "DynamoForRevitUtils.Entities.EqualityComparers.ElementReferenceComparer.yml",
  "DynamoForRevitUtils.Entities.EqualityComparers.ElementReferenceComparer.#ctor": "DynamoForRevitUtils.Entities.EqualityComparers.ElementReferenceComparer.yml",
  "DynamoForRevitUtils.Entities.EqualityComparers.ElementReferenceComparer.Equals(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.Reference)": "DynamoForRevitUtils.Entities.EqualityComparers.ElementReferenceComparer.yml",
  "DynamoForRevitUtils.Entities.EqualityComparers.ElementReferenceComparer.GetHashCode(Autodesk.Revit.DB.Reference)": "DynamoForRevitUtils.Entities.EqualityComparers.ElementReferenceComparer.yml",
  "DynamoForRevitUtils.Entities.GetUnitsResultData": "DynamoForRevitUtils.Entities.GetUnitsResultData.yml",
  "DynamoForRevitUtils.Entities.GetUnitsResultData.#ctor": "DynamoForRevitUtils.Entities.GetUnitsResultData.yml",
  "DynamoForRevitUtils.Entities.GetUnitsResultData.#ctor(Autodesk.Revit.DB.ForgeTypeId,System.String,DynamoForRevitUtils.Enumerations.AccessParameterResult)": "DynamoForRevitUtils.Entities.GetUnitsResultData.yml",
  "DynamoForRevitUtils.Entities.GetUnitsResultData.Description": "DynamoForRevitUtils.Entities.GetUnitsResultData.yml",
  "DynamoForRevitUtils.Entities.GetUnitsResultData.Result": "DynamoForRevitUtils.Entities.GetUnitsResultData.yml",
  "DynamoForRevitUtils.Entities.GetUnitsResultData.UnitTypeOrSpecId": "DynamoForRevitUtils.Entities.GetUnitsResultData.yml",
  "DynamoForRevitUtils.Entities.MEPCurveReferences": "DynamoForRevitUtils.Entities.MEPCurveReferences.yml",
  "DynamoForRevitUtils.Entities.MEPCurveReferences.#ctor(Autodesk.Revit.DB.ReferenceArray,Autodesk.Revit.DB.Curve,Autodesk.DesignScript.Geometry.CoordinateSystem,System.Collections.Generic.List{Autodesk.Revit.DB.Face},Autodesk.Revit.DB.ElementId)": "DynamoForRevitUtils.Entities.MEPCurveReferences.yml",
  "DynamoForRevitUtils.Entities.MEPCurveReferences.EndFaces": "DynamoForRevitUtils.Entities.MEPCurveReferences.yml",
  "DynamoForRevitUtils.Entities.MEPCurveReferences.LocationCurve": "DynamoForRevitUtils.Entities.MEPCurveReferences.yml",
  "DynamoForRevitUtils.Entities.MEPCurveReferences.OwnerId": "DynamoForRevitUtils.Entities.MEPCurveReferences.yml",
  "DynamoForRevitUtils.Entities.MEPCurveReferences.RefArray": "DynamoForRevitUtils.Entities.MEPCurveReferences.yml",
  "DynamoForRevitUtils.Entities.MEPCurveReferences.ReferenceCS": "DynamoForRevitUtils.Entities.MEPCurveReferences.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers": "DynamoForRevitUtils.Entities.ParametersHandlers.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions.#ctor": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions.AccessMode": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions.CheckIfValueContainsInvalidChars": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions.DoubleParameterConvertionMode": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions.GetElementIdValueAsString": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions.Regex": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.#ctor(DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo)": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.#ctor(DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter,System.String,DynamoForRevitUtils.Enumerations.AccessParameterResult)": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.Description": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.EqualityContract": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.Equals(DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo)": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.Equals(System.Object)": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.GetHashCode": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.Parameter": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.PrintMembers(System.Text.StringBuilder)": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.Result": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.ToString": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.op_Equality(DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo,DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo)": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.op_Inequality(DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo,DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo)": "DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.#ctor(Autodesk.Revit.DB.BuiltInParameter,DynamoForRevitUtils.Enumerations.ParameterDataType,DynamoForRevitUtils.Enumerations.ParameterKind)": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.#ctor(Autodesk.Revit.DB.Parameter)": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.#ctor(Autodesk.Revit.DB.Parameter,DynamoForRevitUtils.Enumerations.ParameterKind)": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.#ctor(System.String,DynamoForRevitUtils.Enumerations.ParameterDataType,DynamoForRevitUtils.Enumerations.ParameterKind)": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.BuiltInParameter": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.Clone": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.DataType": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.Definition": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.Document": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.Equals(System.Object)": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.GetDisplayUnits": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.GetHashCode": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.GetValueFromRevitParameter(DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions)": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.Id": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.Invalid": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.IsBuiltInParameter": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.Kind": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.Name": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.OwnerElement": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.RevitParameter": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.SetValueToRevitParameter": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.Spec": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.SpecTypeId": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.ToString": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.Unit": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.UnitTypeId": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.Value": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.op_Equality(DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter,DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter)": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.op_Inequality(DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter,DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter)": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor-1.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1.#ctor(DynamoForRevitUtils.Entities.Wrappers.IElementWrapper{`0})": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor-1.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1.GetBoolValue(System.String)": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor-1.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1.GetDoubleValue(System.String)": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor-1.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1.GetElementIdValue(System.String)": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor-1.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1.GetIntegerValue(System.String)": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor-1.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1.GetStringValue(System.String)": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor-1.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor`1.SetValue(System.Object,System.String)": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterAccessor-1.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMapItem": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMapItem.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMapItem.#ctor": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMapItem.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMapItem.ElementParameter": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMapItem.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMapItem.PropertyName": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMapItem.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMap`1": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMap-1.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMap`1.#ctor": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMap-1.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMap`1.GetItems": "DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameterMap-1.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.IElementParameterMap": "DynamoForRevitUtils.Entities.ParametersHandlers.IElementParameterMap.yml",
  "DynamoForRevitUtils.Entities.ParametersHandlers.IElementParameterMap.GetItems": "DynamoForRevitUtils.Entities.ParametersHandlers.IElementParameterMap.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters": "DynamoForRevitUtils.Entities.PickSelectionFilters.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.CategorySelectionFilter": "DynamoForRevitUtils.Entities.PickSelectionFilters.CategorySelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.CategorySelectionFilter.#ctor(System.Boolean,Autodesk.Revit.DB.BuiltInCategory)": "DynamoForRevitUtils.Entities.PickSelectionFilters.CategorySelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.CategorySelectionFilter.AllowElement(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Entities.PickSelectionFilters.CategorySelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.CategorySelectionFilter.AllowReference(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.XYZ)": "DynamoForRevitUtils.Entities.PickSelectionFilters.CategorySelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.MultiCategorySelectionFilter": "DynamoForRevitUtils.Entities.PickSelectionFilters.MultiCategorySelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.MultiCategorySelectionFilter.#ctor(System.Boolean,Autodesk.Revit.DB.BuiltInCategory[])": "DynamoForRevitUtils.Entities.PickSelectionFilters.MultiCategorySelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.MultiCategorySelectionFilter.AllowElement(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Entities.PickSelectionFilters.MultiCategorySelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.MultiCategorySelectionFilter.AllowReference(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.XYZ)": "DynamoForRevitUtils.Entities.PickSelectionFilters.MultiCategorySelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.NoFilter": "DynamoForRevitUtils.Entities.PickSelectionFilters.NoFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.NoFilter.#ctor": "DynamoForRevitUtils.Entities.PickSelectionFilters.NoFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.NoFilter.AllowElement(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Entities.PickSelectionFilters.NoFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.NoFilter.AllowReference(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.XYZ)": "DynamoForRevitUtils.Entities.PickSelectionFilters.NoFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter": "DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter.#ctor": "DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter.#ctor(System.Boolean,System.Collections.Generic.IEnumerable{Autodesk.Revit.DB.BuiltInCategory})": "DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter.AllowElement(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter.AllowLinkedElements": "DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter.AllowReference(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.XYZ)": "DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter.Categories": "DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.WallSelectionFilter": "DynamoForRevitUtils.Entities.PickSelectionFilters.WallSelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.WallSelectionFilter.#ctor(Autodesk.Revit.DB.WallKind,System.Boolean)": "DynamoForRevitUtils.Entities.PickSelectionFilters.WallSelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.WallSelectionFilter.AllowElement(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Entities.PickSelectionFilters.WallSelectionFilter.yml",
  "DynamoForRevitUtils.Entities.PickSelectionFilters.WallSelectionFilter.AllowReference(Autodesk.Revit.DB.Reference,Autodesk.Revit.DB.XYZ)": "DynamoForRevitUtils.Entities.PickSelectionFilters.WallSelectionFilter.yml",
  "DynamoForRevitUtils.Entities.Section": "DynamoForRevitUtils.Entities.Section.yml",
  "DynamoForRevitUtils.Entities.Section.Create(Autodesk.Revit.DB.Document,DynamoForRevitUtils.Entities.SectionCreationData,Autodesk.Revit.DB.ViewFamilyType,System.UInt16,System.Boolean,Autodesk.Revit.DB.View)": "DynamoForRevitUtils.Entities.Section.yml",
  "DynamoForRevitUtils.Entities.Section.Data": "DynamoForRevitUtils.Entities.Section.yml",
  "DynamoForRevitUtils.Entities.Section.SectionView": "DynamoForRevitUtils.Entities.Section.yml",
  "DynamoForRevitUtils.Entities.SectionCreationData": "DynamoForRevitUtils.Entities.SectionCreationData.yml",
  "DynamoForRevitUtils.Entities.SectionCreationData.#ctor(DynamoForRevitUtils.Entities.Axis,System.Double,System.Double)": "DynamoForRevitUtils.Entities.SectionCreationData.yml",
  "DynamoForRevitUtils.Entities.SectionCreationData.#ctor(DynamoForRevitUtils.Entities.Axis,System.Double,System.Double,System.Double,System.Double,System.Double,System.Double)": "DynamoForRevitUtils.Entities.SectionCreationData.yml",
  "DynamoForRevitUtils.Entities.SectionCreationData.Axis": "DynamoForRevitUtils.Entities.SectionCreationData.yml",
  "DynamoForRevitUtils.Entities.SectionCreationData.CropValue": "DynamoForRevitUtils.Entities.SectionCreationData.yml",
  "DynamoForRevitUtils.Entities.SectionCreationData.FarClipOffset": "DynamoForRevitUtils.Entities.SectionCreationData.yml",
  "DynamoForRevitUtils.Entities.SectionCreationData.XNegOffset": "DynamoForRevitUtils.Entities.SectionCreationData.yml",
  "DynamoForRevitUtils.Entities.SectionCreationData.XPosOffset": "DynamoForRevitUtils.Entities.SectionCreationData.yml",
  "DynamoForRevitUtils.Entities.SectionCreationData.YNegOffset": "DynamoForRevitUtils.Entities.SectionCreationData.yml",
  "DynamoForRevitUtils.Entities.SectionCreationData.YPosOffset": "DynamoForRevitUtils.Entities.SectionCreationData.yml",
  "DynamoForRevitUtils.Entities.SelectionResults": "DynamoForRevitUtils.Entities.SelectionResults.yml",
  "DynamoForRevitUtils.Entities.SelectionResults.#ctor": "DynamoForRevitUtils.Entities.SelectionResults.yml",
  "DynamoForRevitUtils.Entities.SelectionResults.ActiveView": "DynamoForRevitUtils.Entities.SelectionResults.yml",
  "DynamoForRevitUtils.Entities.SelectionResults.Elements": "DynamoForRevitUtils.Entities.SelectionResults.yml",
  "DynamoForRevitUtils.Entities.SelectionResults.GroupByCategory": "DynamoForRevitUtils.Entities.SelectionResults.yml",
  "DynamoForRevitUtils.Entities.SelectionResults.GroupedElements": "DynamoForRevitUtils.Entities.SelectionResults.yml",
  "DynamoForRevitUtils.Entities.SelectionResults.GroupedRevitLinkInstances": "DynamoForRevitUtils.Entities.SelectionResults.yml",
  "DynamoForRevitUtils.Entities.SelectionResults.RevitLinkInstances": "DynamoForRevitUtils.Entities.SelectionResults.yml",
  "DynamoForRevitUtils.Entities.SelectionResults.Settings": "DynamoForRevitUtils.Entities.SelectionResults.yml",
  "DynamoForRevitUtils.Entities.SelectionResults.ToDictionary": "DynamoForRevitUtils.Entities.SelectionResults.yml",
  "DynamoForRevitUtils.Entities.SelectionResults.ToString": "DynamoForRevitUtils.Entities.SelectionResults.yml",
  "DynamoForRevitUtils.Entities.SelectionSettings": "DynamoForRevitUtils.Entities.SelectionSettings.yml",
  "DynamoForRevitUtils.Entities.SelectionSettings.#ctor(Autodesk.Revit.DB.ElementFilter)": "DynamoForRevitUtils.Entities.SelectionSettings.yml",
  "DynamoForRevitUtils.Entities.SelectionSettings.#ctor(System.String,Autodesk.Revit.UI.Selection.ObjectType)": "DynamoForRevitUtils.Entities.SelectionSettings.yml",
  "DynamoForRevitUtils.Entities.SelectionSettings.#ctor(System.String,Autodesk.Revit.UI.Selection.ObjectType,DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter)": "DynamoForRevitUtils.Entities.SelectionSettings.yml",
  "DynamoForRevitUtils.Entities.SelectionSettings.#ctor(System.String,Autodesk.Revit.UI.Selection.ObjectType,DynamoForRevitUtils.Entities.PickSelectionFilters.PickSelectionFilter,Autodesk.Revit.DB.ElementFilter)": "DynamoForRevitUtils.Entities.SelectionSettings.yml",
  "DynamoForRevitUtils.Entities.SelectionSettings.CollectorFilter": "DynamoForRevitUtils.Entities.SelectionSettings.yml",
  "DynamoForRevitUtils.Entities.SelectionSettings.ObjectType": "DynamoForRevitUtils.Entities.SelectionSettings.yml",
  "DynamoForRevitUtils.Entities.SelectionSettings.PickSelectionFilter": "DynamoForRevitUtils.Entities.SelectionSettings.yml",
  "DynamoForRevitUtils.Entities.SelectionSettings.Prompt": "DynamoForRevitUtils.Entities.SelectionSettings.yml",
  "DynamoForRevitUtils.Entities.SelectionSettings.ShowElementsSelectionDialog(System.String,System.String)": "DynamoForRevitUtils.Entities.SelectionSettings.yml",
  "DynamoForRevitUtils.Entities.SelectionSettings.ToString": "DynamoForRevitUtils.Entities.SelectionSettings.yml",
  "DynamoForRevitUtils.Entities.WallElevation": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.#ctor(System.String,Autodesk.Revit.DB.Wall,Autodesk.Revit.DB.ViewFamilyType,System.Double,System.Boolean,DynamoForRevitUtils.Entities.CropRegionOffsetSettings)": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.CreateElevationView(Autodesk.Revit.DB.ViewPlan,System.Int32,Autodesk.Revit.DB.RevitLinkInstance,System.Boolean)": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.CropRegionOffsetSettings": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.Elevation": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.ElevationMarker": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.ElevationPoint": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.FarClipOffset": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.Flipped": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.Name": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.OffsetFromWall": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.Scale": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.ToString": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.ViewFamilyType": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.Wall": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.WallBaseLine": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.WallCenterPoint": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.WallLocationCurve": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.WallMidPoint": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.WallElevation.WallNormal": "DynamoForRevitUtils.Entities.WallElevation.yml",
  "DynamoForRevitUtils.Entities.Wrappers": "DynamoForRevitUtils.Entities.Wrappers.yml",
  "DynamoForRevitUtils.Entities.Wrappers.ElementWrapper`1": "DynamoForRevitUtils.Entities.Wrappers.ElementWrapper-1.yml",
  "DynamoForRevitUtils.Entities.Wrappers.ElementWrapper`1.#ctor(Autodesk.Revit.DB.Element,`0)": "DynamoForRevitUtils.Entities.Wrappers.ElementWrapper-1.yml",
  "DynamoForRevitUtils.Entities.Wrappers.ElementWrapper`1.Element": "DynamoForRevitUtils.Entities.Wrappers.ElementWrapper-1.yml",
  "DynamoForRevitUtils.Entities.Wrappers.ElementWrapper`1.ParameterAccessor": "DynamoForRevitUtils.Entities.Wrappers.ElementWrapper-1.yml",
  "DynamoForRevitUtils.Entities.Wrappers.ElementWrapper`1.ParameterMap": "DynamoForRevitUtils.Entities.Wrappers.ElementWrapper-1.yml",
  "DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper`1": "DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper-1.yml",
  "DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper`1.#ctor(Autodesk.Revit.DB.FamilyInstance,`0)": "DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper-1.yml",
  "DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper`1.FamilyInstance": "DynamoForRevitUtils.Entities.Wrappers.FamilyInstanceWrapper-1.yml",
  "DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1": "DynamoForRevitUtils.Entities.Wrappers.IElementWrapper-1.yml",
  "DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1.Element": "DynamoForRevitUtils.Entities.Wrappers.IElementWrapper-1.yml",
  "DynamoForRevitUtils.Entities.Wrappers.IElementWrapper`1.ParameterMap": "DynamoForRevitUtils.Entities.Wrappers.IElementWrapper-1.yml",
  "DynamoForRevitUtils.Enumerations": "DynamoForRevitUtils.Enumerations.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterMode": "DynamoForRevitUtils.Enumerations.AccessParameterMode.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterMode.ParameterOnly": "DynamoForRevitUtils.Enumerations.AccessParameterMode.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterMode.ParameterWithValue": "DynamoForRevitUtils.Enumerations.AccessParameterMode.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.ElementNotFound": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.InvalidDataType": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.InvalidElementKind": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.InvalidParameter": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.InvalidSpecTypeId": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.InvalidUnitTypeId": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.InvalidValue": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.NullElementParameter": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.ParameterFound": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.ParameterNotFound": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.UnitFound": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.UnknownError": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.ValueFound": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.ValueNotFound": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.AccessParameterResult.ValueSet": "DynamoForRevitUtils.Enumerations.AccessParameterResult.yml",
  "DynamoForRevitUtils.Enumerations.Coordinate": "DynamoForRevitUtils.Enumerations.Coordinate.yml",
  "DynamoForRevitUtils.Enumerations.Coordinate.X": "DynamoForRevitUtils.Enumerations.Coordinate.yml",
  "DynamoForRevitUtils.Enumerations.Coordinate.Y": "DynamoForRevitUtils.Enumerations.Coordinate.yml",
  "DynamoForRevitUtils.Enumerations.Coordinate.Z": "DynamoForRevitUtils.Enumerations.Coordinate.yml",
  "DynamoForRevitUtils.Enumerations.DoubleParameterConvertionMode": "DynamoForRevitUtils.Enumerations.DoubleParameterConvertionMode.yml",
  "DynamoForRevitUtils.Enumerations.DoubleParameterConvertionMode.UseActiveDocumentUnits": "DynamoForRevitUtils.Enumerations.DoubleParameterConvertionMode.yml",
  "DynamoForRevitUtils.Enumerations.DoubleParameterConvertionMode.UseElementDocumentUnits": "DynamoForRevitUtils.Enumerations.DoubleParameterConvertionMode.yml",
  "DynamoForRevitUtils.Enumerations.ElementParameterYesNoValue": "DynamoForRevitUtils.Enumerations.ElementParameterYesNoValue.yml",
  "DynamoForRevitUtils.Enumerations.ElementParameterYesNoValue.No": "DynamoForRevitUtils.Enumerations.ElementParameterYesNoValue.yml",
  "DynamoForRevitUtils.Enumerations.ElementParameterYesNoValue.Yes": "DynamoForRevitUtils.Enumerations.ElementParameterYesNoValue.yml",
  "DynamoForRevitUtils.Enumerations.ParameterDataType": "DynamoForRevitUtils.Enumerations.ParameterDataType.yml",
  "DynamoForRevitUtils.Enumerations.ParameterDataType.Boolean": "DynamoForRevitUtils.Enumerations.ParameterDataType.yml",
  "DynamoForRevitUtils.Enumerations.ParameterDataType.Decimal": "DynamoForRevitUtils.Enumerations.ParameterDataType.yml",
  "DynamoForRevitUtils.Enumerations.ParameterDataType.ElementId": "DynamoForRevitUtils.Enumerations.ParameterDataType.yml",
  "DynamoForRevitUtils.Enumerations.ParameterDataType.Integer": "DynamoForRevitUtils.Enumerations.ParameterDataType.yml",
  "DynamoForRevitUtils.Enumerations.ParameterDataType.Text": "DynamoForRevitUtils.Enumerations.ParameterDataType.yml",
  "DynamoForRevitUtils.Enumerations.ParameterDataType.Undefined": "DynamoForRevitUtils.Enumerations.ParameterDataType.yml",
  "DynamoForRevitUtils.Enumerations.ParameterDataType.YesNo": "DynamoForRevitUtils.Enumerations.ParameterDataType.yml",
  "DynamoForRevitUtils.Enumerations.ParameterKind": "DynamoForRevitUtils.Enumerations.ParameterKind.yml",
  "DynamoForRevitUtils.Enumerations.ParameterKind.Instance": "DynamoForRevitUtils.Enumerations.ParameterKind.yml",
  "DynamoForRevitUtils.Enumerations.ParameterKind.Type": "DynamoForRevitUtils.Enumerations.ParameterKind.yml",
  "DynamoForRevitUtils.Enumerations.ParameterKind.Undefined": "DynamoForRevitUtils.Enumerations.ParameterKind.yml",
  "DynamoForRevitUtils.Enumerations.ParameterValidationResult": "DynamoForRevitUtils.Enumerations.ParameterValidationResult.yml",
  "DynamoForRevitUtils.Enumerations.ParameterValidationResult.InvalidValue": "DynamoForRevitUtils.Enumerations.ParameterValidationResult.yml",
  "DynamoForRevitUtils.Enumerations.ParameterValidationResult.NotConvertibleValue": "DynamoForRevitUtils.Enumerations.ParameterValidationResult.yml",
  "DynamoForRevitUtils.Enumerations.ParameterValidationResult.NotFound": "DynamoForRevitUtils.Enumerations.ParameterValidationResult.yml",
  "DynamoForRevitUtils.Enumerations.ParameterValidationResult.UndefinedStorageType": "DynamoForRevitUtils.Enumerations.ParameterValidationResult.yml",
  "DynamoForRevitUtils.Enumerations.ParameterValidationResult.ValidValue": "DynamoForRevitUtils.Enumerations.ParameterValidationResult.yml",
  "DynamoForRevitUtils.Enumerations.RoofLineType": "DynamoForRevitUtils.Enumerations.RoofLineType.yml",
  "DynamoForRevitUtils.Enumerations.RoofLineType.Eave": "DynamoForRevitUtils.Enumerations.RoofLineType.yml",
  "DynamoForRevitUtils.Enumerations.RoofLineType.Hip": "DynamoForRevitUtils.Enumerations.RoofLineType.yml",
  "DynamoForRevitUtils.Enumerations.RoofLineType.Ridge": "DynamoForRevitUtils.Enumerations.RoofLineType.yml",
  "DynamoForRevitUtils.Enumerations.RoofLineType.Undefined": "DynamoForRevitUtils.Enumerations.RoofLineType.yml",
  "DynamoForRevitUtils.Enumerations.RoofLineType.Valley": "DynamoForRevitUtils.Enumerations.RoofLineType.yml",
  "DynamoForRevitUtils.Enumerations.SelectionMethod": "DynamoForRevitUtils.Enumerations.SelectionMethod.yml",
  "DynamoForRevitUtils.Enumerations.SelectionMethod.AllElements": "DynamoForRevitUtils.Enumerations.SelectionMethod.yml",
  "DynamoForRevitUtils.Enumerations.SelectionMethod.AllElementsFromActiveView": "DynamoForRevitUtils.Enumerations.SelectionMethod.yml",
  "DynamoForRevitUtils.Enumerations.SelectionMethod.Manual": "DynamoForRevitUtils.Enumerations.SelectionMethod.yml",
  "DynamoForRevitUtils.Services.Collections": "DynamoForRevitUtils.Services.Collections.yml",
  "DynamoForRevitUtils.Services.Collections.EnumerableServices": "DynamoForRevitUtils.Services.Collections.EnumerableServices.yml",
  "DynamoForRevitUtils.Services.Collections.EnumerableServices.DoIfHasAny``1(System.Collections.Generic.IEnumerable{``0},System.Action{System.Collections.Generic.IEnumerable{``0}})": "DynamoForRevitUtils.Services.Collections.EnumerableServices.yml",
  "DynamoForRevitUtils.Services.Collections.EnumerableServices.DoIfHasAny``1(System.Collections.Generic.IEnumerable{``0},System.Predicate{``0},System.Action{System.Collections.Generic.IEnumerable{``0}})": "DynamoForRevitUtils.Services.Collections.EnumerableServices.yml",
  "DynamoForRevitUtils.Services.Collections.EnumerableServices.HasAny``1(System.Collections.Generic.IEnumerable{``0})": "DynamoForRevitUtils.Services.Collections.EnumerableServices.yml",
  "DynamoForRevitUtils.Services.Collections.EnumerableServices.HasAny``1(System.Collections.Generic.IEnumerable{``0},System.Predicate{``0})": "DynamoForRevitUtils.Services.Collections.EnumerableServices.yml",
  "DynamoForRevitUtils.Services.Collectors": "DynamoForRevitUtils.Services.Collectors.yml",
  "DynamoForRevitUtils.Services.Collectors.CategoryCollectors": "DynamoForRevitUtils.Services.Collectors.CategoryCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.CategoryCollectors.GetAllRevitCategories(Autodesk.Revit.DB.Document,System.Nullable{Autodesk.Revit.DB.CategoryType})": "DynamoForRevitUtils.Services.Collectors.CategoryCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.CategoryCollectors.GetLinesSubCategories(Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.Collectors.CategoryCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.CategoryCollectors.GetTagCategories": "DynamoForRevitUtils.Services.Collectors.CategoryCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.GenericCollectors": "DynamoForRevitUtils.Services.Collectors.GenericCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.GenericCollectors.GetAllElementTypesOfCategory``1(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.BuiltInCategory)": "DynamoForRevitUtils.Services.Collectors.GenericCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.GenericCollectors.GetAllElementTypesOfClass``1(Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.Collectors.GenericCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.GenericCollectors.GetAllElementsOfCategory``1(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.BuiltInCategory,Autodesk.Revit.DB.View,Autodesk.Revit.DB.ElementFilter)": "DynamoForRevitUtils.Services.Collectors.GenericCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.GenericCollectors.GetAllElementsOfClass``1(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.View,Autodesk.Revit.DB.ElementFilter)": "DynamoForRevitUtils.Services.Collectors.GenericCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.GenericCollectors.GetAllFamilySymbolsOfCategory(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.BuiltInCategory)": "DynamoForRevitUtils.Services.Collectors.GenericCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.LineStyleCollectors": "DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllCutStyles(Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.AllProjectionStyles(Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.Collectors.LineStyleCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.PhaseCollectors": "DynamoForRevitUtils.Services.Collectors.PhaseCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.PhaseCollectors.GetPhaseIdByName(Autodesk.Revit.DB.Document,System.String)": "DynamoForRevitUtils.Services.Collectors.PhaseCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.RoomCollectors": "DynamoForRevitUtils.Services.Collectors.RoomCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.RoomCollectors.GetAllInvalidRooms(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.View)": "DynamoForRevitUtils.Services.Collectors.RoomCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.RoomCollectors.GetAllRoomSeparationLines(Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.Collectors.RoomCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.RoomCollectors.GetAllValidRooms(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.View)": "DynamoForRevitUtils.Services.Collectors.RoomCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.RoomCollectors.GetRoomFinishes(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.Architecture.Room,Autodesk.Revit.DB.SpatialElementGeometryCalculator,Autodesk.Revit.DB.SubfaceType,System.Boolean)": "DynamoForRevitUtils.Services.Collectors.RoomCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.RoomCollectors.GetRoomSeparationLinesFromDesignOption(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId)": "DynamoForRevitUtils.Services.Collectors.RoomCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.RoomCollectors.GetValidRoomsFromActiveDesignOption(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.View)": "DynamoForRevitUtils.Services.Collectors.RoomCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.RoomCollectors.GetValidRoomsFromDesignOption(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ElementId)": "DynamoForRevitUtils.Services.Collectors.RoomCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.WallCollectors": "DynamoForRevitUtils.Services.Collectors.WallCollectors.yml",
  "DynamoForRevitUtils.Services.Collectors.WallCollectors.GetBasic(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.View)": "DynamoForRevitUtils.Services.Collectors.WallCollectors.yml",
  "DynamoForRevitUtils.Services.Dynamo": "DynamoForRevitUtils.Services.Dynamo.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.AddPoint(Autodesk.DesignScript.Geometry.BoundingBox,Autodesk.DesignScript.Geometry.Point)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetBottomCenter(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetBottomSurface(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetBottomSurfaceDiagonal(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetCentroid(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetDiagonal(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetDiagonalLength(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetEdges(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetHeight(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetLength(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetOppositeBottomSurfaceDiagonal(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetSurfaces(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetTopCenter(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetTopSurface(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetVertices(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.GetWidth(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.Offset(Autodesk.DesignScript.Geometry.BoundingBox,System.Double)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.ToBoundingBoxXYZ(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.ToCoordinateSystem(Autodesk.DesignScript.Geometry.BoundingBox)": "DynamoForRevitUtils.Services.Dynamo.BoundingBoxServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.ArePointsCollinear(Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point,System.Double)": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.ComputeAverageCenterPoint(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Point})": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.GetMeshSurfaces(Autodesk.DesignScript.Geometry.Mesh)": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.GetMidPoint(Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point)": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.GetRelativeCoordinatesOfPoint(Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.CoordinateSystem)": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.GroupAlignedLines(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Line},System.Double)": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.IsHorizontal(Autodesk.DesignScript.Geometry.Surface,System.UInt16)": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.IsParallelTo(Autodesk.DesignScript.Geometry.Vector,Autodesk.DesignScript.Geometry.Vector,System.UInt16)": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.IsPerpendicularTo(Autodesk.DesignScript.Geometry.Vector,Autodesk.DesignScript.Geometry.Vector,System.UInt16)": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.IsVertical(Autodesk.DesignScript.Geometry.Surface,System.UInt16)": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.ReorderLines(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Line})": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.SwapCoordinateValue(Autodesk.DesignScript.Geometry.Point,DynamoForRevitUtils.Enumerations.Coordinate,System.Double)": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.SwapCoordinateValue(Autodesk.DesignScript.Geometry.Vector,DynamoForRevitUtils.Enumerations.Coordinate,System.Double)": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.ToPolyCurve(System.Collections.Generic.IEnumerable{Autodesk.DesignScript.Geometry.Curve})": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.Visualize(Autodesk.DesignScript.Geometry.BoundingBox,DSCore.Color,System.Boolean)": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.Visualize(Autodesk.DesignScript.Geometry.CoordinateSystem,System.Double)": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.Visualize(Autodesk.DesignScript.Geometry.Vector,Autodesk.DesignScript.Geometry.Point,DSCore.Color,System.Double)": "DynamoForRevitUtils.Services.Dynamo.DynamoGeometryServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.JoinLinesServices": "DynamoForRevitUtils.Services.Dynamo.JoinLinesServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.JoinLinesServices.JoinLinesIntoClosedPolyCurve(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Line},System.Boolean)": "DynamoForRevitUtils.Services.Dynamo.JoinLinesServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices": "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.GetProtoLocation(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.ToBuiltInCategory(Revit.Elements.Category)": "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.ToDynamoCategory(Autodesk.Revit.DB.BuiltInCategory)": "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.ToDynamoType(Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.ToRevitDocument(Revit.Application.Document)": "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.TryConvertToDSType``1(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.UnwrapElement``1(Revit.Elements.Element)": "DynamoForRevitUtils.Services.Dynamo.RevitElementsServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.TopographyServices": "DynamoForRevitUtils.Services.Dynamo.TopographyServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.TopographyServices.#ctor": "DynamoForRevitUtils.Services.Dynamo.TopographyServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.TopographyServices.GetTopographySurfaces(Revit.Elements.Topography)": "DynamoForRevitUtils.Services.Dynamo.TopographyServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.TopographyServices.PointProject(System.Collections.Generic.List{Autodesk.DesignScript.Geometry.Surface},Autodesk.DesignScript.Geometry.Point)": "DynamoForRevitUtils.Services.Dynamo.TopographyServices.yml",
  "DynamoForRevitUtils.Services.Dynamo.TopographyServices.TopographyToPolySurface(Revit.Elements.Topography)": "DynamoForRevitUtils.Services.Dynamo.TopographyServices.yml",
  "DynamoForRevitUtils.Services.Enumerations": "DynamoForRevitUtils.Services.Enumerations.yml",
  "DynamoForRevitUtils.Services.Enumerations.Converters": "DynamoForRevitUtils.Services.Enumerations.Converters.yml",
  "DynamoForRevitUtils.Services.Enumerations.Converters.ToParameterDataType(Autodesk.Revit.DB.StorageType)": "DynamoForRevitUtils.Services.Enumerations.Converters.yml",
  "DynamoForRevitUtils.Services.Enumerations.Converters.ToStorageType(DynamoForRevitUtils.Enumerations.ParameterDataType)": "DynamoForRevitUtils.Services.Enumerations.Converters.yml",
  "DynamoForRevitUtils.Services.Enumerations.EnumParser": "DynamoForRevitUtils.Services.Enumerations.EnumParser.yml",
  "DynamoForRevitUtils.Services.Enumerations.EnumParser.ByValue(System.String,System.String,System.String)": "DynamoForRevitUtils.Services.Enumerations.EnumParser.yml",
  "DynamoForRevitUtils.Services.Enumerations.EnumParser.ByValue``1(System.Object)": "DynamoForRevitUtils.Services.Enumerations.EnumParser.yml",
  "DynamoForRevitUtils.Services.Enumerations.EnumParser.ByValue``1(System.String)": "DynamoForRevitUtils.Services.Enumerations.EnumParser.yml",
  "DynamoForRevitUtils.Services.Files": "DynamoForRevitUtils.Services.Files.yml",
  "DynamoForRevitUtils.Services.Files.CSV": "DynamoForRevitUtils.Services.Files.CSV.yml",
  "DynamoForRevitUtils.Services.Files.CSV.ReadFileFromPath(System.String,System.String,System.Boolean,System.Boolean,System.Object,System.Object)": "DynamoForRevitUtils.Services.Files.CSV.yml",
  "DynamoForRevitUtils.Services.Files.CSV.WriteToFilePath(System.String,System.Object[][],System.String)": "DynamoForRevitUtils.Services.Files.CSV.yml",
  "DynamoForRevitUtils.Services.Files.Excel": "DynamoForRevitUtils.Services.Files.Excel.yml",
  "DynamoForRevitUtils.Services.Files.Excel.GetValidSheetName(System.String)": "DynamoForRevitUtils.Services.Files.Excel.yml",
  "DynamoForRevitUtils.Services.GenericServices": "DynamoForRevitUtils.Services.GenericServices.yml",
  "DynamoForRevitUtils.Services.GenericServices.ObjectServices": "DynamoForRevitUtils.Services.GenericServices.ObjectServices.yml",
  "DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)": "DynamoForRevitUtils.Services.GenericServices.ObjectServices.yml",
  "DynamoForRevitUtils.Services.MathServices": "DynamoForRevitUtils.Services.MathServices.yml",
  "DynamoForRevitUtils.Services.MathServices.ArithmeticServices": "DynamoForRevitUtils.Services.MathServices.ArithmeticServices.yml",
  "DynamoForRevitUtils.Services.MathServices.ArithmeticServices.GetDecimalPlaces(System.Decimal)": "DynamoForRevitUtils.Services.MathServices.ArithmeticServices.yml",
  "DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices": "DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices.yml",
  "DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices.GetRelativeCoordinatesOfPoint(Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.CoordinateSystem)": "DynamoForRevitUtils.Services.MathServices.LinearAlgebraServices.yml",
  "DynamoForRevitUtils.Services.MathServices.RangeServices": "DynamoForRevitUtils.Services.MathServices.RangeServices.yml",
  "DynamoForRevitUtils.Services.MathServices.RangeServices.StartEndAmount(System.Double,System.Double,System.UInt16)": "DynamoForRevitUtils.Services.MathServices.RangeServices.yml",
  "DynamoForRevitUtils.Services.MathServices.RangeServices.StartEndStep(System.Double,System.Double,System.Double)": "DynamoForRevitUtils.Services.MathServices.RangeServices.yml",
  "DynamoForRevitUtils.Services.MathServices.RangeServices.StartEndStep(System.Double,System.Double,System.Double,System.Boolean)": "DynamoForRevitUtils.Services.MathServices.RangeServices.yml",
  "DynamoForRevitUtils.Services.MathServices.SequenceServices": "DynamoForRevitUtils.Services.MathServices.SequenceServices.yml",
  "DynamoForRevitUtils.Services.MathServices.SequenceServices.ArithmeticProgression(System.Double,System.UInt16,System.Double)": "DynamoForRevitUtils.Services.MathServices.SequenceServices.yml",
  "DynamoForRevitUtils.Services.Reflection": "DynamoForRevitUtils.Services.Reflection.yml",
  "DynamoForRevitUtils.Services.Reflection.ReflectionServices": "DynamoForRevitUtils.Services.Reflection.ReflectionServices.yml",
  "DynamoForRevitUtils.Services.Reflection.ReflectionServices.GetDelegateFullName(System.Delegate)": "DynamoForRevitUtils.Services.Reflection.ReflectionServices.yml",
  "DynamoForRevitUtils.Services.Reflection.ReflectionServices.GetDelegateInfo(System.Delegate,System.String)": "DynamoForRevitUtils.Services.Reflection.ReflectionServices.yml",
  "DynamoForRevitUtils.Services.Reflection.ReflectionServices.GetExecutingAssemblyPath": "DynamoForRevitUtils.Services.Reflection.ReflectionServices.yml",
  "DynamoForRevitUtils.Services.Reflection.ReflectionServices.GetTypeByFullNameAndAssemblyPath(System.String,System.String)": "DynamoForRevitUtils.Services.Reflection.ReflectionServices.yml",
  "DynamoForRevitUtils.Services.RevitServices": "DynamoForRevitUtils.Services.RevitServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.CategoryServices": "DynamoForRevitUtils.Services.RevitServices.CategoryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.CategoryServices.GetElementId(Autodesk.Revit.DB.BuiltInCategory)": "DynamoForRevitUtils.Services.RevitServices.CategoryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.CategoryServices.IsAnnotationCategory(Autodesk.Revit.DB.BuiltInCategory)": "DynamoForRevitUtils.Services.RevitServices.CategoryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.CategoryServices.IsAnnotationCategory(Autodesk.Revit.DB.Category)": "DynamoForRevitUtils.Services.RevitServices.CategoryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.CategoryServices.IsModelCategory(Autodesk.Revit.DB.BuiltInCategory)": "DynamoForRevitUtils.Services.RevitServices.CategoryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.CategoryServices.IsModelCategory(Autodesk.Revit.DB.Category)": "DynamoForRevitUtils.Services.RevitServices.CategoryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.CategoryServices.ToBuiltInCategory(Autodesk.Revit.DB.Category)": "DynamoForRevitUtils.Services.RevitServices.CategoryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.CategoryServices.ToRevitCategory(Autodesk.Revit.DB.BuiltInCategory,Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.RevitServices.CategoryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.DesignOptionServices": "DynamoForRevitUtils.Services.RevitServices.DesignOptionServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.DesignOptionServices.GetActiveDesignOptionId(Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.RevitServices.DesignOptionServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.DocumentServices": "DynamoForRevitUtils.Services.RevitServices.DocumentServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.DocumentServices.BatchOpenDocuments(System.String,Autodesk.Revit.UI.UIApplication)": "DynamoForRevitUtils.Services.RevitServices.DocumentServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.DocumentServices.GetName(Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.RevitServices.DocumentServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.DocumentServices.GetPath(Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.RevitServices.DocumentServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.DocumentServices.OpenDocument(System.String,Autodesk.Revit.UI.UIApplication)": "DynamoForRevitUtils.Services.RevitServices.DocumentServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementIdServices": "DynamoForRevitUtils.Services.RevitServices.ElementIdServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementIdServices.GetElementId(System.Int64)": "DynamoForRevitUtils.Services.RevitServices.ElementIdServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementIdServices.GetElement``1(Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.RevitServices.ElementIdServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementIdServices.GetElement``1(System.String,Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.RevitServices.ElementIdServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementIdServices.GetValue(Autodesk.Revit.DB.ElementId)": "DynamoForRevitUtils.Services.RevitServices.ElementIdServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementIdServices.IsValidId(Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.RevitServices.ElementIdServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.BelongsToLinkedModel(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.RevitLinkInstance)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.CheckAnnotationsClashes(System.Collections.Generic.IEnumerable{Autodesk.Revit.DB.Element},Autodesk.Revit.DB.Color)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetAnnotationOutline(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.View,System.Double)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetBoundingBox(Autodesk.Revit.DB.Element,System.Double,Autodesk.Revit.DB.RevitLinkInstance)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetBoundingBoxFilter(Autodesk.Revit.DB.Element,System.Double,Autodesk.Revit.DB.RevitLinkInstance)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetElementsBoundingBox(Autodesk.Revit.DB.Document,System.Collections.Generic.List{Autodesk.Revit.DB.Element})": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetFacesByDirection(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Document,Autodesk.Revit.DB.XYZ)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetLevel(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetLineBasedBoundLine(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetLineBasedDirection(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetLocationAsPoint(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetNearbyElements(Autodesk.Revit.DB.Element,System.Collections.Generic.List{Autodesk.Revit.DB.BuiltInCategory},Autodesk.Revit.DB.Document,System.Double)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetParameter(Autodesk.Revit.DB.Element,DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter,DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetParameters(Autodesk.Revit.DB.Element,System.Collections.Generic.IEnumerable{DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter},DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetRooms(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetRooms(Autodesk.Revit.DB.Element,System.Collections.Generic.IEnumerable{Autodesk.Revit.DB.Architecture.Room})": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.GetSolids(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.Options)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.HasParameter(Autodesk.Revit.DB.Element,DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter,System.Text.RegularExpressions.Regex,DynamoForRevitUtils.Entities.ParametersHandlers.AccessParameterInfo@)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.IsAnnotationElement(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.IsCutByView(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.View,System.Collections.Generic.List{Autodesk.Revit.DB.Solid}@,Autodesk.Revit.DB.RevitLinkInstance,Autodesk.Revit.DB.Options,System.Double)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.IsFromCategory(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.BuiltInCategory)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.IsLineBased(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.IsLinked(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.IsLinkedElement(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.IsModelInPlace(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.IsValidElement(Autodesk.Revit.DB.Element)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.SetElementsOverrides(System.Collections.Generic.List{Autodesk.Revit.DB.Element},Autodesk.Revit.DB.View,Autodesk.Revit.DB.OverrideGraphicSettings)": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ElementServices.SetParameters(Autodesk.Revit.DB.Element,DynamoForRevitUtils.Entities.ParametersHandlers.AccessElementParameterOptions,System.Collections.Generic.IEnumerable{DynamoForRevitUtils.Entities.ParametersHandlers.ElementParameter})": "DynamoForRevitUtils.Services.RevitServices.ElementServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices": "DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices.GetAllNestedFamilies(Autodesk.Revit.DB.FamilyInstance)": "DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices.GetCuboid(Autodesk.Revit.DB.FamilyInstance,Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices.GetReferenceByName(Autodesk.Revit.DB.FamilyInstance,System.String)": "DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices.GetReferenceByType(Autodesk.Revit.DB.FamilyInstance,Autodesk.Revit.DB.FamilyInstanceReferenceType)": "DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices.GetSolids(Autodesk.Revit.DB.FamilyInstance,Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices.GetSolidsFromGeometryObjects(System.Collections.Generic.List{Autodesk.Revit.DB.GeometryObject})": "DynamoForRevitUtils.Services.RevitServices.FamilyInstanceServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.GridServices": "DynamoForRevitUtils.Services.RevitServices.GridServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.GridServices.DistanceToPoint(Autodesk.Revit.DB.Grid,Autodesk.Revit.DB.XYZ)": "DynamoForRevitUtils.Services.RevitServices.GridServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.GridServices.GetDirection(Autodesk.Revit.DB.Grid,System.Double)": "DynamoForRevitUtils.Services.RevitServices.GridServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.GridServices.GetPlane(Autodesk.Revit.DB.Grid,System.Double)": "DynamoForRevitUtils.Services.RevitServices.GridServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.GridServices.ProjectPoint(Autodesk.Revit.DB.Grid,Autodesk.Revit.DB.XYZ)": "DynamoForRevitUtils.Services.RevitServices.GridServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ImportInstanceServices": "DynamoForRevitUtils.Services.RevitServices.ImportInstanceServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ImportInstanceServices.GetLevel(Autodesk.Revit.DB.ImportInstance)": "DynamoForRevitUtils.Services.RevitServices.ImportInstanceServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.LevelServices": "DynamoForRevitUtils.Services.RevitServices.LevelServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.LevelServices.GetNearestLevel(Autodesk.Revit.DB.Document,System.Double,System.UInt16,System.Boolean)": "DynamoForRevitUtils.Services.RevitServices.LevelServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.LevelServices.GetNearestLevel(Autodesk.Revit.DB.Level,System.Boolean)": "DynamoForRevitUtils.Services.RevitServices.LevelServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.MEPCurveServices": "DynamoForRevitUtils.Services.RevitServices.MEPCurveServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.MEPCurveServices.GetReferences(Autodesk.Revit.DB.MEPCurve)": "DynamoForRevitUtils.Services.RevitServices.MEPCurveServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices": "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.ArePointsCollinear(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,System.Double)": "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.CreateByRectangle(Autodesk.DesignScript.Geometry.Rectangle)": "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.DistanceToPlane(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.Plane)": "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.DistanceToPoint(Autodesk.Revit.DB.Plane,Autodesk.Revit.DB.XYZ)": "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.GetMidPoint(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ)": "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.GetOuterCurves(Autodesk.Revit.DB.Face)": "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.IsParallelTo(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,System.UInt16)": "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.IsPerpendicularTo(Autodesk.Revit.DB.XYZ,Autodesk.Revit.DB.XYZ,System.UInt16)": "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.SwapCoordinateValue(Autodesk.Revit.DB.XYZ,DynamoForRevitUtils.Enumerations.Coordinate,System.Double)": "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.ToProtoBoundingBox(Autodesk.Revit.DB.BoundingBoxXYZ)": "DynamoForRevitUtils.Services.RevitServices.RevitGeometryServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagCreationService": "DynamoForRevitUtils.Services.RevitServices.TagCreationService.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagCreationService.#ctor": "DynamoForRevitUtils.Services.RevitServices.TagCreationService.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagCreationService.CreateTag": "DynamoForRevitUtils.Services.RevitServices.TagCreationService.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagCreationService.SetTagLocationAndHeadPositionOnFloorPlan(DynamoForRevitUtils.Services.RevitServices.TagInfo)": "DynamoForRevitUtils.Services.RevitServices.TagCreationService.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagCreationService.SetTagLocationAndHeadPositionOnSection(DynamoForRevitUtils.Services.RevitServices.TagInfo)": "DynamoForRevitUtils.Services.RevitServices.TagCreationService.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagCreationService.ValidCategories": "DynamoForRevitUtils.Services.RevitServices.TagCreationService.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagCreationService._tagInfo": "DynamoForRevitUtils.Services.RevitServices.TagCreationService.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagInfo": "DynamoForRevitUtils.Services.RevitServices.TagInfo.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagInfo.#ctor(Autodesk.Revit.DB.Element,Autodesk.Revit.DB.ElementId,Autodesk.Revit.DB.ElementId,System.Double,Autodesk.Revit.DB.RevitLinkInstance,System.Boolean)": "DynamoForRevitUtils.Services.RevitServices.TagInfo.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagInfo.AddLeader": "DynamoForRevitUtils.Services.RevitServices.TagInfo.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagInfo.Element": "DynamoForRevitUtils.Services.RevitServices.TagInfo.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagInfo.LeaderElbow": "DynamoForRevitUtils.Services.RevitServices.TagInfo.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagInfo.LeaderEnd": "DynamoForRevitUtils.Services.RevitServices.TagInfo.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagInfo.LinkInstance": "DynamoForRevitUtils.Services.RevitServices.TagInfo.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagInfo.Location": "DynamoForRevitUtils.Services.RevitServices.TagInfo.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagInfo.Offset": "DynamoForRevitUtils.Services.RevitServices.TagInfo.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagInfo.OwnerView": "DynamoForRevitUtils.Services.RevitServices.TagInfo.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagInfo.OwnerViewId": "DynamoForRevitUtils.Services.RevitServices.TagInfo.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagInfo.SymbolId": "DynamoForRevitUtils.Services.RevitServices.TagInfo.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagInfo.TagHeadPosition": "DynamoForRevitUtils.Services.RevitServices.TagInfo.yml",
  "DynamoForRevitUtils.Services.RevitServices.TagInfo.TagReference": "DynamoForRevitUtils.Services.RevitServices.TagInfo.yml",
  "DynamoForRevitUtils.Services.RevitServices.TaskDialogServices": "DynamoForRevitUtils.Services.RevitServices.TaskDialogServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.TaskDialogServices.ShowDecisionDialog(System.String,System.String,System.Boolean,System.String)": "DynamoForRevitUtils.Services.RevitServices.TaskDialogServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.TaskDialogServices.ShowError(System.String,System.String,System.String)": "DynamoForRevitUtils.Services.RevitServices.TaskDialogServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.TaskDialogServices.ShowInformation(System.String,System.String,System.String)": "DynamoForRevitUtils.Services.RevitServices.TaskDialogServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.TaskDialogServices.ShowMultiChoiceDialog(System.String,System.String,System.String,System.String,System.String,System.String)": "DynamoForRevitUtils.Services.RevitServices.TaskDialogServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.TaskDialogServices.ShowWarning(System.String,System.String,System.String)": "DynamoForRevitUtils.Services.RevitServices.TaskDialogServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ViewServices": "DynamoForRevitUtils.Services.RevitServices.ViewServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ViewServices.GetActiveUIView(Autodesk.Revit.UI.UIDocument)": "DynamoForRevitUtils.Services.RevitServices.ViewServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ViewServices.GetCuboid(Autodesk.Revit.DB.View3D)": "DynamoForRevitUtils.Services.RevitServices.ViewServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ViewServices.GetPlane(Autodesk.Revit.DB.View)": "DynamoForRevitUtils.Services.RevitServices.ViewServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ViewServices.PickPointOnActive2DView(System.String,System.Boolean,System.Nullable{Autodesk.Revit.UI.Selection.ObjectSnapTypes})": "DynamoForRevitUtils.Services.RevitServices.ViewServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ViewServices.TrySet2DViewPlaneAsWorkPlane(Autodesk.Revit.DB.View)": "DynamoForRevitUtils.Services.RevitServices.ViewServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.ViewServices.Validate2DViewToPlaceAnnotations(Autodesk.Revit.DB.View,System.Boolean)": "DynamoForRevitUtils.Services.RevitServices.ViewServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetBasicWallsNearby(Autodesk.Revit.DB.Wall)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetBottomSurface(Autodesk.Revit.DB.Wall)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetExtendedLocation(Autodesk.Revit.DB.Wall,System.Double)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetExtendedLocationLine(Autodesk.Revit.DB.Wall,System.Double)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetExtendedSolid(Autodesk.Revit.DB.Wall,System.Double)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetExtremitiesSurfaces(Autodesk.Revit.DB.Wall)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetFairwayVerticalSurfaces(Autodesk.Revit.DB.Wall,System.Double)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetFrontalSurfaces(Autodesk.Revit.DB.Wall)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetHorizontalSurfaces(Autodesk.Revit.DB.Wall)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetJoinedElementsAtEnds(Autodesk.Revit.DB.Wall)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetJoinedElementsAtEnds(Autodesk.Revit.DB.Wall,Autodesk.Revit.DB.BuiltInCategory)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetLateralSurfaces(Autodesk.Revit.DB.Wall)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetParallelGrids(Autodesk.Revit.DB.Wall,Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetPhysicalLocation(Autodesk.Revit.DB.Wall)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetProtoSolid(Autodesk.Revit.DB.Wall)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetTopFace(Autodesk.Revit.DB.Wall)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.RevitServices.WallServices.GetVerticalSurfaces(Autodesk.Revit.DB.Wall)": "DynamoForRevitUtils.Services.RevitServices.WallServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion": "DynamoForRevitUtils.Services.UnitsConversion.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices": "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.ConvertBetweenUnits(System.Double,Autodesk.Revit.DB.ForgeTypeId,Autodesk.Revit.DB.ForgeTypeId)": "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.ConvertDisplayToInternalUnit(System.Double,Autodesk.Revit.DB.ForgeTypeId,Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.ConvertFromDisplayUnit(System.Double,Autodesk.Revit.DB.ForgeTypeId,Autodesk.Revit.DB.ForgeTypeId,Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.ConvertFromInternalUnit(System.Double,Autodesk.Revit.DB.ForgeTypeId,Autodesk.Revit.DB.ForgeTypeId)": "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.ConvertInternalToDisplayUnit(System.Double,Autodesk.Revit.DB.ForgeTypeId,Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.ConvertToDisplayUnit(System.Double,Autodesk.Revit.DB.ForgeTypeId,Autodesk.Revit.DB.ForgeTypeId,Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.ConvertToInternalUnit(System.Double,Autodesk.Revit.DB.ForgeTypeId,Autodesk.Revit.DB.ForgeTypeId)": "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.DisplayMassDensityToInternalUnit(System.Double,Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.InternalMassDensityToDisplayUnit(System.Double,Autodesk.Revit.DB.Document)": "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.InternalMassDensityToKilogramsPerCubicMeter(System.Double)": "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.InternalMassDensityToPoundsMassPerCubicFoot(System.Double)": "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.KilogramsPerCubicMeterToInternal(System.Double)": "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.PoundsMassPerCubicFootToInternal(System.Double)": "DynamoForRevitUtils.Services.UnitsConversion.ConversionServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.SpecificFactorsServices": "DynamoForRevitUtils.Services.UnitsConversion.SpecificFactorsServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.SpecificFactorsServices.GetMassDensityConversionFactorByDisplayUnits(Autodesk.Revit.DB.ForgeTypeId)": "DynamoForRevitUtils.Services.UnitsConversion.SpecificFactorsServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.SpecificFactorsServices.KilogramsPerCubicMeter_To_KilogramsPerCubicFoot": "DynamoForRevitUtils.Services.UnitsConversion.SpecificFactorsServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.SpecificFactorsServices.PoundsMassPerCubicFoot_To_KilogramsPerCubicFoot": "DynamoForRevitUtils.Services.UnitsConversion.SpecificFactorsServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.UnitsServices": "DynamoForRevitUtils.Services.UnitsConversion.UnitsServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.UnitsServices.ChangeDisplayUnit(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ForgeTypeId,Autodesk.Revit.DB.ForgeTypeId)": "DynamoForRevitUtils.Services.UnitsConversion.UnitsServices.yml",
  "DynamoForRevitUtils.Services.UnitsConversion.UnitsServices.GetDisplayUnit(Autodesk.Revit.DB.Document,Autodesk.Revit.DB.ForgeTypeId)": "DynamoForRevitUtils.Services.UnitsConversion.UnitsServices.yml"
}