### YamlMime:ManagedReference
items:
- uid: DynamoForRevitUtils.Entities.Axis
  commentId: T:DynamoForRevitUtils.Entities.Axis
  id: Axis
  parent: DynamoForRevitUtils.Entities
  children:
  - DynamoForRevitUtils.Entities.Axis.#ctor(System.String,Autodesk.DesignScript.Geometry.Line)
  - DynamoForRevitUtils.Entities.Axis.#ctor(System.String,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point)
  - DynamoForRevitUtils.Entities.Axis.#ctor(System.String,System.Double,System.Double,System.Double,System.Double,System.Double)
  - DynamoForRevitUtils.Entities.Axis.CoordinateSystem
  - DynamoForRevitUtils.Entities.Axis.Direction
  - DynamoForRevitUtils.Entities.Axis.Elevation
  - DynamoForRevitUtils.Entities.Axis.EndPoint
  - DynamoForRevitUtils.Entities.Axis.IsPerpendicular
  - DynamoForRevitUtils.Entities.Axis.IsTranslated
  - DynamoForRevitUtils.Entities.Axis.Length
  - DynamoForRevitUtils.Entities.Axis.Line
  - DynamoForRevitUtils.Entities.Axis.Name
  - DynamoForRevitUtils.Entities.Axis.Normal
  - DynamoForRevitUtils.Entities.Axis.Perpendicular(System.Double,System.Nullable{System.Double},System.Boolean,System.Double,System.Double)
  - DynamoForRevitUtils.Entities.Axis.StartPoint
  - DynamoForRevitUtils.Entities.Axis.Translate(Autodesk.DesignScript.Geometry.Vector,System.Double)
  langs:
  - csharp
  - vb
  name: Axis
  nameWithType: Axis
  fullName: DynamoForRevitUtils.Entities.Axis
  type: Class
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Represents an axis in the DynamoForRevitUtils library.
  remarks: Axis are used to create Section Views in Revit.
  example: []
  syntax:
    content: >-
      [IsVisibleInDynamoLibrary(false)]

      public class Axis
    content.vb: >-
      <IsVisibleInDynamoLibrary(False)>

      Public Class Axis
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  extensionMethods:
  - System.Object.DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1
  attributes:
  - type: Autodesk.DesignScript.Runtime.IsVisibleInDynamoLibraryAttribute
    ctor: Autodesk.DesignScript.Runtime.IsVisibleInDynamoLibraryAttribute.#ctor(System.Boolean)
    arguments:
    - type: System.Boolean
      value: false
- uid: DynamoForRevitUtils.Entities.Axis.#ctor(System.String,System.Double,System.Double,System.Double,System.Double,System.Double)
  commentId: M:DynamoForRevitUtils.Entities.Axis.#ctor(System.String,System.Double,System.Double,System.Double,System.Double,System.Double)
  id: '#ctor(System.String,System.Double,System.Double,System.Double,System.Double,System.Double)'
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: Axis(string, double, double, double, double, double)
  nameWithType: Axis.Axis(string, double, double, double, double, double)
  fullName: DynamoForRevitUtils.Entities.Axis.Axis(string, double, double, double, double, double)
  type: Constructor
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Constructs an Axis object by it's extremities coordinates
  example: []
  syntax:
    content: public Axis(string name, double x1, double y1, double x2, double y2, double elevation = 0)
    parameters:
    - id: name
      type: System.String
      description: Axis name
    - id: x1
      type: System.Double
      description: Start point X coordinate in Revit Document Display Units
    - id: y1
      type: System.Double
      description: Start point Y coordinate in Revit Document Display Units
    - id: x2
      type: System.Double
      description: End point X coordinate in Revit Document Display Units
    - id: y2
      type: System.Double
      description: End point Y coordinate in Revit Document Display Units
    - id: elevation
      type: System.Double
      description: Axis elevation in Revit Document Display Units
    content.vb: Public Sub New(name As String, x1 As Double, y1 As Double, x2 As Double, y2 As Double, elevation As Double = 0)
  overload: DynamoForRevitUtils.Entities.Axis.#ctor*
  nameWithType.vb: Axis.New(String, Double, Double, Double, Double, Double)
  fullName.vb: DynamoForRevitUtils.Entities.Axis.New(String, Double, Double, Double, Double, Double)
  name.vb: New(String, Double, Double, Double, Double, Double)
- uid: DynamoForRevitUtils.Entities.Axis.#ctor(System.String,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point)
  commentId: M:DynamoForRevitUtils.Entities.Axis.#ctor(System.String,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point)
  id: '#ctor(System.String,Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point)'
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: Axis(string, Point, Point)
  nameWithType: Axis.Axis(string, Point, Point)
  fullName: DynamoForRevitUtils.Entities.Axis.Axis(string, Autodesk.DesignScript.Geometry.Point, Autodesk.DesignScript.Geometry.Point)
  type: Constructor
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Constructs an Axis object by Start Point, End Point
  example: []
  syntax:
    content: public Axis(string name, Point startPoint, Point endPoint)
    parameters:
    - id: name
      type: System.String
      description: Axis name
    - id: startPoint
      type: Autodesk.DesignScript.Geometry.Point
      description: Axis start point
    - id: endPoint
      type: Autodesk.DesignScript.Geometry.Point
      description: Axis end point
    content.vb: Public Sub New(name As String, startPoint As Point, endPoint As Point)
  overload: DynamoForRevitUtils.Entities.Axis.#ctor*
  nameWithType.vb: Axis.New(String, Point, Point)
  fullName.vb: DynamoForRevitUtils.Entities.Axis.New(String, Autodesk.DesignScript.Geometry.Point, Autodesk.DesignScript.Geometry.Point)
  name.vb: New(String, Point, Point)
- uid: DynamoForRevitUtils.Entities.Axis.#ctor(System.String,Autodesk.DesignScript.Geometry.Line)
  commentId: M:DynamoForRevitUtils.Entities.Axis.#ctor(System.String,Autodesk.DesignScript.Geometry.Line)
  id: '#ctor(System.String,Autodesk.DesignScript.Geometry.Line)'
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: Axis(string, Line)
  nameWithType: Axis.Axis(string, Line)
  fullName: DynamoForRevitUtils.Entities.Axis.Axis(string, Autodesk.DesignScript.Geometry.Line)
  type: Constructor
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Constructs an Axis object by it's Dynamo Line representation
  example: []
  syntax:
    content: public Axis(string name, Line line)
    parameters:
    - id: name
      type: System.String
      description: Axis name
    - id: line
      type: Autodesk.DesignScript.Geometry.Line
      description: Axis Dynamo Line
    content.vb: Public Sub New(name As String, line As Line)
  overload: DynamoForRevitUtils.Entities.Axis.#ctor*
  nameWithType.vb: Axis.New(String, Line)
  fullName.vb: DynamoForRevitUtils.Entities.Axis.New(String, Autodesk.DesignScript.Geometry.Line)
  name.vb: New(String, Line)
- uid: DynamoForRevitUtils.Entities.Axis.Perpendicular(System.Double,System.Nullable{System.Double},System.Boolean,System.Double,System.Double)
  commentId: M:DynamoForRevitUtils.Entities.Axis.Perpendicular(System.Double,System.Nullable{System.Double},System.Boolean,System.Double,System.Double)
  id: Perpendicular(System.Double,System.Nullable{System.Double},System.Boolean,System.Double,System.Double)
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: Perpendicular(double, double?, bool, double, double)
  nameWithType: Axis.Perpendicular(double, double?, bool, double, double)
  fullName: DynamoForRevitUtils.Entities.Axis.Perpendicular(double, double?, bool, double, double)
  type: Method
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Perpendicular Axis from original axis
  example: []
  syntax:
    content: public Axis Perpendicular(double parameter = 0, double? length = null, bool reverse = false, double xOffset = 0, double yOffset = 0)
    parameters:
    - id: parameter
      type: System.Double
      description: A value between 0 and 1, representing the position of the Perpendicular Axis along the original axis
    - id: length
      type: System.Nullable{System.Double}
      description: The length of the Perpendicular Axis
    - id: reverse
      type: System.Boolean
      description: Reverse the Perpendicular Axis
    - id: xOffset
      type: System.Double
      description: Perpendicular Axis offset on original axis normal direction
    - id: yOffset
      type: System.Double
      description: Perpendicular Axis offset on original axis direction
    return:
      type: DynamoForRevitUtils.Entities.Axis
      description: Perpendicular Axis
    content.vb: Public Function Perpendicular(parameter As Double = 0, length As Double? = Nothing, reverse As Boolean = False, xOffset As Double = 0, yOffset As Double = 0) As Axis
  overload: DynamoForRevitUtils.Entities.Axis.Perpendicular*
  nameWithType.vb: Axis.Perpendicular(Double, Double?, Boolean, Double, Double)
  fullName.vb: DynamoForRevitUtils.Entities.Axis.Perpendicular(Double, Double?, Boolean, Double, Double)
  name.vb: Perpendicular(Double, Double?, Boolean, Double, Double)
- uid: DynamoForRevitUtils.Entities.Axis.Translate(Autodesk.DesignScript.Geometry.Vector,System.Double)
  commentId: M:DynamoForRevitUtils.Entities.Axis.Translate(Autodesk.DesignScript.Geometry.Vector,System.Double)
  id: Translate(Autodesk.DesignScript.Geometry.Vector,System.Double)
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: Translate(Vector, double)
  nameWithType: Axis.Translate(Vector, double)
  fullName: DynamoForRevitUtils.Entities.Axis.Translate(Autodesk.DesignScript.Geometry.Vector, double)
  type: Method
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Translates the Axis
  example: []
  syntax:
    content: public Axis Translate(Vector direction, double distance = 0)
    parameters:
    - id: direction
      type: Autodesk.DesignScript.Geometry.Vector
      description: Dynamo Vector representing the translation direction
    - id: distance
      type: System.Double
      description: Translation distance
    return:
      type: DynamoForRevitUtils.Entities.Axis
      description: Translated Axis
    content.vb: Public Function Translate(direction As Vector, distance As Double = 0) As Axis
  overload: DynamoForRevitUtils.Entities.Axis.Translate*
  nameWithType.vb: Axis.Translate(Vector, Double)
  fullName.vb: DynamoForRevitUtils.Entities.Axis.Translate(Autodesk.DesignScript.Geometry.Vector, Double)
  name.vb: Translate(Vector, Double)
- uid: DynamoForRevitUtils.Entities.Axis.Elevation
  commentId: P:DynamoForRevitUtils.Entities.Axis.Elevation
  id: Elevation
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: Elevation
  nameWithType: Axis.Elevation
  fullName: DynamoForRevitUtils.Entities.Axis.Elevation
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Axis elevation (Z value)
  example: []
  syntax:
    content: public double Elevation { get; set; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public Property Elevation As Double
  overload: DynamoForRevitUtils.Entities.Axis.Elevation*
- uid: DynamoForRevitUtils.Entities.Axis.Name
  commentId: P:DynamoForRevitUtils.Entities.Axis.Name
  id: Name
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: Axis.Name
  fullName: DynamoForRevitUtils.Entities.Axis.Name
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Axis name
  example: []
  syntax:
    content: public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: DynamoForRevitUtils.Entities.Axis.Name*
- uid: DynamoForRevitUtils.Entities.Axis.StartPoint
  commentId: P:DynamoForRevitUtils.Entities.Axis.StartPoint
  id: StartPoint
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: StartPoint
  nameWithType: Axis.StartPoint
  fullName: DynamoForRevitUtils.Entities.Axis.StartPoint
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Axis start point
  example: []
  syntax:
    content: public Point StartPoint { get; set; }
    parameters: []
    return:
      type: Autodesk.DesignScript.Geometry.Point
    content.vb: Public Property StartPoint As Point
  overload: DynamoForRevitUtils.Entities.Axis.StartPoint*
- uid: DynamoForRevitUtils.Entities.Axis.EndPoint
  commentId: P:DynamoForRevitUtils.Entities.Axis.EndPoint
  id: EndPoint
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: EndPoint
  nameWithType: Axis.EndPoint
  fullName: DynamoForRevitUtils.Entities.Axis.EndPoint
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Axis end point
  example: []
  syntax:
    content: public Point EndPoint { get; set; }
    parameters: []
    return:
      type: Autodesk.DesignScript.Geometry.Point
    content.vb: Public Property EndPoint As Point
  overload: DynamoForRevitUtils.Entities.Axis.EndPoint*
- uid: DynamoForRevitUtils.Entities.Axis.Direction
  commentId: P:DynamoForRevitUtils.Entities.Axis.Direction
  id: Direction
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: Direction
  nameWithType: Axis.Direction
  fullName: DynamoForRevitUtils.Entities.Axis.Direction
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Axis direction
  example: []
  syntax:
    content: public Vector Direction { get; set; }
    parameters: []
    return:
      type: Autodesk.DesignScript.Geometry.Vector
    content.vb: Public Property Direction As Vector
  overload: DynamoForRevitUtils.Entities.Axis.Direction*
- uid: DynamoForRevitUtils.Entities.Axis.Line
  commentId: P:DynamoForRevitUtils.Entities.Axis.Line
  id: Line
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: Line
  nameWithType: Axis.Line
  fullName: DynamoForRevitUtils.Entities.Axis.Line
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Dynamo representation of the Axis
  example: []
  syntax:
    content: public Line Line { get; set; }
    parameters: []
    return:
      type: Autodesk.DesignScript.Geometry.Line
    content.vb: Public Property Line As Line
  overload: DynamoForRevitUtils.Entities.Axis.Line*
- uid: DynamoForRevitUtils.Entities.Axis.Length
  commentId: P:DynamoForRevitUtils.Entities.Axis.Length
  id: Length
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: Length
  nameWithType: Axis.Length
  fullName: DynamoForRevitUtils.Entities.Axis.Length
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Axis length in Revit Document Display Units
  example: []
  syntax:
    content: public double Length { get; set; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public Property Length As Double
  overload: DynamoForRevitUtils.Entities.Axis.Length*
- uid: DynamoForRevitUtils.Entities.Axis.CoordinateSystem
  commentId: P:DynamoForRevitUtils.Entities.Axis.CoordinateSystem
  id: CoordinateSystem
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: CoordinateSystem
  nameWithType: Axis.CoordinateSystem
  fullName: DynamoForRevitUtils.Entities.Axis.CoordinateSystem
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Dynamo representation of the Axis coordinate system
  example: []
  syntax:
    content: public CoordinateSystem CoordinateSystem { get; set; }
    parameters: []
    return:
      type: Autodesk.DesignScript.Geometry.CoordinateSystem
    content.vb: Public Property CoordinateSystem As CoordinateSystem
  overload: DynamoForRevitUtils.Entities.Axis.CoordinateSystem*
- uid: DynamoForRevitUtils.Entities.Axis.Normal
  commentId: P:DynamoForRevitUtils.Entities.Axis.Normal
  id: Normal
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: Normal
  nameWithType: Axis.Normal
  fullName: DynamoForRevitUtils.Entities.Axis.Normal
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Dynamo representation of the Axis Normal
  example: []
  syntax:
    content: public Vector Normal { get; set; }
    parameters: []
    return:
      type: Autodesk.DesignScript.Geometry.Vector
    content.vb: Public Property Normal As Vector
  overload: DynamoForRevitUtils.Entities.Axis.Normal*
- uid: DynamoForRevitUtils.Entities.Axis.IsPerpendicular
  commentId: P:DynamoForRevitUtils.Entities.Axis.IsPerpendicular
  id: IsPerpendicular
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: IsPerpendicular
  nameWithType: Axis.IsPerpendicular
  fullName: DynamoForRevitUtils.Entities.Axis.IsPerpendicular
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Indicates if the Axis is perpendicular
  example: []
  syntax:
    content: public bool IsPerpendicular { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsPerpendicular As Boolean
  overload: DynamoForRevitUtils.Entities.Axis.IsPerpendicular*
- uid: DynamoForRevitUtils.Entities.Axis.IsTranslated
  commentId: P:DynamoForRevitUtils.Entities.Axis.IsTranslated
  id: IsTranslated
  parent: DynamoForRevitUtils.Entities.Axis
  langs:
  - csharp
  - vb
  name: IsTranslated
  nameWithType: Axis.IsTranslated
  fullName: DynamoForRevitUtils.Entities.Axis.IsTranslated
  type: Property
  assemblies:
  - DynamoForRevitUtils
  namespace: DynamoForRevitUtils.Entities
  summary: Indicates if the Axis is translated
  example: []
  syntax:
    content: public bool IsTranslated { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsTranslated As Boolean
  overload: DynamoForRevitUtils.Entities.Axis.IsTranslated*
references:
- uid: DynamoForRevitUtils.Entities
  commentId: N:DynamoForRevitUtils.Entities
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Entities
  nameWithType: DynamoForRevitUtils.Entities
  fullName: DynamoForRevitUtils.Entities
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Entities
    name: Entities
    isExternal: true
    href: DynamoForRevitUtils.Entities.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Entities
    name: Entities
    isExternal: true
    href: DynamoForRevitUtils.Entities.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1
  commentId: M:DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  parent: DynamoForRevitUtils.Services.GenericServices.ObjectServices
  definition: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  name: TryCast<T>(object)
  nameWithType: ObjectServices.TryCast<T>(object)
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast<T>(object)
  nameWithType.vb: ObjectServices.TryCast(Of T)(Object)
  fullName.vb: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast(Of T)(Object)
  name.vb: TryCast(Of T)(Object)
  spec.csharp:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  commentId: M:DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
  isExternal: true
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  name: TryCast<T>(object)
  nameWithType: ObjectServices.TryCast<T>(object)
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast<T>(object)
  nameWithType.vb: ObjectServices.TryCast(Of T)(Object)
  fullName.vb: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast(Of T)(Object)
  name.vb: TryCast(Of T)(Object)
  spec.csharp:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: <
  - name: T
  - name: '>'
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices.TryCast``1(System.Object)
    name: TryCast
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html#DynamoForRevitUtils_Services_GenericServices_ObjectServices_TryCast__1_System_Object_
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: DynamoForRevitUtils.Services.GenericServices.ObjectServices
  commentId: T:DynamoForRevitUtils.Services.GenericServices.ObjectServices
  parent: DynamoForRevitUtils.Services.GenericServices
  isExternal: true
  href: DynamoForRevitUtils.Services.GenericServices.ObjectServices.html
  name: ObjectServices
  nameWithType: ObjectServices
  fullName: DynamoForRevitUtils.Services.GenericServices.ObjectServices
- uid: DynamoForRevitUtils.Services.GenericServices
  commentId: N:DynamoForRevitUtils.Services.GenericServices
  isExternal: true
  href: DynamoForRevitUtils.html
  name: DynamoForRevitUtils.Services.GenericServices
  nameWithType: DynamoForRevitUtils.Services.GenericServices
  fullName: DynamoForRevitUtils.Services.GenericServices
  spec.csharp:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.GenericServices
    name: GenericServices
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.html
  spec.vb:
  - uid: DynamoForRevitUtils
    name: DynamoForRevitUtils
    isExternal: true
    href: DynamoForRevitUtils.html
  - name: .
  - uid: DynamoForRevitUtils.Services
    name: Services
    isExternal: true
    href: DynamoForRevitUtils.Services.html
  - name: .
  - uid: DynamoForRevitUtils.Services.GenericServices
    name: GenericServices
    isExternal: true
    href: DynamoForRevitUtils.Services.GenericServices.html
- uid: DynamoForRevitUtils.Entities.Axis.#ctor*
  commentId: Overload:DynamoForRevitUtils.Entities.Axis.#ctor
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html#DynamoForRevitUtils_Entities_Axis__ctor_System_String_System_Double_System_Double_System_Double_System_Double_System_Double_
  name: Axis
  nameWithType: Axis.Axis
  fullName: DynamoForRevitUtils.Entities.Axis.Axis
  nameWithType.vb: Axis.New
  fullName.vb: DynamoForRevitUtils.Entities.Axis.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Double
  commentId: T:System.Double
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.double
  name: double
  nameWithType: double
  fullName: double
  nameWithType.vb: Double
  fullName.vb: Double
  name.vb: Double
- uid: Autodesk.DesignScript.Geometry.Point
  commentId: T:Autodesk.DesignScript.Geometry.Point
  parent: Autodesk.DesignScript.Geometry
  isExternal: true
  name: Point
  nameWithType: Point
  fullName: Autodesk.DesignScript.Geometry.Point
- uid: Autodesk.DesignScript.Geometry
  commentId: N:Autodesk.DesignScript.Geometry
  isExternal: true
  name: Autodesk.DesignScript.Geometry
  nameWithType: Autodesk.DesignScript.Geometry
  fullName: Autodesk.DesignScript.Geometry
  spec.csharp:
  - uid: Autodesk
    name: Autodesk
    isExternal: true
  - name: .
  - uid: Autodesk.DesignScript
    name: DesignScript
    isExternal: true
  - name: .
  - uid: Autodesk.DesignScript.Geometry
    name: Geometry
    isExternal: true
  spec.vb:
  - uid: Autodesk
    name: Autodesk
    isExternal: true
  - name: .
  - uid: Autodesk.DesignScript
    name: DesignScript
    isExternal: true
  - name: .
  - uid: Autodesk.DesignScript.Geometry
    name: Geometry
    isExternal: true
- uid: Autodesk.DesignScript.Geometry.Line
  commentId: T:Autodesk.DesignScript.Geometry.Line
  parent: Autodesk.DesignScript.Geometry
  isExternal: true
  name: Line
  nameWithType: Line
  fullName: Autodesk.DesignScript.Geometry.Line
- uid: DynamoForRevitUtils.Entities.Axis.Perpendicular*
  commentId: Overload:DynamoForRevitUtils.Entities.Axis.Perpendicular
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html#DynamoForRevitUtils_Entities_Axis_Perpendicular_System_Double_System_Nullable_System_Double__System_Boolean_System_Double_System_Double_
  name: Perpendicular
  nameWithType: Axis.Perpendicular
  fullName: DynamoForRevitUtils.Entities.Axis.Perpendicular
- uid: System.Nullable{System.Double}
  commentId: T:System.Nullable{System.Double}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.double
  name: double?
  nameWithType: double?
  fullName: double?
  nameWithType.vb: Double?
  fullName.vb: Double?
  name.vb: Double?
  spec.csharp:
  - uid: System.Double
    name: double
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.double
  - name: '?'
  spec.vb:
  - uid: System.Double
    name: Double
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.double
  - name: '?'
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: DynamoForRevitUtils.Entities.Axis
  commentId: T:DynamoForRevitUtils.Entities.Axis
  parent: DynamoForRevitUtils.Entities
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html
  name: Axis
  nameWithType: Axis
  fullName: DynamoForRevitUtils.Entities.Axis
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: DynamoForRevitUtils.Entities.Axis.Translate*
  commentId: Overload:DynamoForRevitUtils.Entities.Axis.Translate
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html#DynamoForRevitUtils_Entities_Axis_Translate_Autodesk_DesignScript_Geometry_Vector_System_Double_
  name: Translate
  nameWithType: Axis.Translate
  fullName: DynamoForRevitUtils.Entities.Axis.Translate
- uid: Autodesk.DesignScript.Geometry.Vector
  commentId: T:Autodesk.DesignScript.Geometry.Vector
  parent: Autodesk.DesignScript.Geometry
  isExternal: true
  name: Vector
  nameWithType: Vector
  fullName: Autodesk.DesignScript.Geometry.Vector
- uid: DynamoForRevitUtils.Entities.Axis.Elevation*
  commentId: Overload:DynamoForRevitUtils.Entities.Axis.Elevation
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html#DynamoForRevitUtils_Entities_Axis_Elevation
  name: Elevation
  nameWithType: Axis.Elevation
  fullName: DynamoForRevitUtils.Entities.Axis.Elevation
- uid: DynamoForRevitUtils.Entities.Axis.Name*
  commentId: Overload:DynamoForRevitUtils.Entities.Axis.Name
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html#DynamoForRevitUtils_Entities_Axis_Name
  name: Name
  nameWithType: Axis.Name
  fullName: DynamoForRevitUtils.Entities.Axis.Name
- uid: DynamoForRevitUtils.Entities.Axis.StartPoint*
  commentId: Overload:DynamoForRevitUtils.Entities.Axis.StartPoint
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html#DynamoForRevitUtils_Entities_Axis_StartPoint
  name: StartPoint
  nameWithType: Axis.StartPoint
  fullName: DynamoForRevitUtils.Entities.Axis.StartPoint
- uid: DynamoForRevitUtils.Entities.Axis.EndPoint*
  commentId: Overload:DynamoForRevitUtils.Entities.Axis.EndPoint
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html#DynamoForRevitUtils_Entities_Axis_EndPoint
  name: EndPoint
  nameWithType: Axis.EndPoint
  fullName: DynamoForRevitUtils.Entities.Axis.EndPoint
- uid: DynamoForRevitUtils.Entities.Axis.Direction*
  commentId: Overload:DynamoForRevitUtils.Entities.Axis.Direction
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html#DynamoForRevitUtils_Entities_Axis_Direction
  name: Direction
  nameWithType: Axis.Direction
  fullName: DynamoForRevitUtils.Entities.Axis.Direction
- uid: DynamoForRevitUtils.Entities.Axis.Line*
  commentId: Overload:DynamoForRevitUtils.Entities.Axis.Line
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html#DynamoForRevitUtils_Entities_Axis_Line
  name: Line
  nameWithType: Axis.Line
  fullName: DynamoForRevitUtils.Entities.Axis.Line
- uid: DynamoForRevitUtils.Entities.Axis.Length*
  commentId: Overload:DynamoForRevitUtils.Entities.Axis.Length
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html#DynamoForRevitUtils_Entities_Axis_Length
  name: Length
  nameWithType: Axis.Length
  fullName: DynamoForRevitUtils.Entities.Axis.Length
- uid: DynamoForRevitUtils.Entities.Axis.CoordinateSystem*
  commentId: Overload:DynamoForRevitUtils.Entities.Axis.CoordinateSystem
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html#DynamoForRevitUtils_Entities_Axis_CoordinateSystem
  name: CoordinateSystem
  nameWithType: Axis.CoordinateSystem
  fullName: DynamoForRevitUtils.Entities.Axis.CoordinateSystem
- uid: Autodesk.DesignScript.Geometry.CoordinateSystem
  commentId: T:Autodesk.DesignScript.Geometry.CoordinateSystem
  parent: Autodesk.DesignScript.Geometry
  isExternal: true
  name: CoordinateSystem
  nameWithType: CoordinateSystem
  fullName: Autodesk.DesignScript.Geometry.CoordinateSystem
- uid: DynamoForRevitUtils.Entities.Axis.Normal*
  commentId: Overload:DynamoForRevitUtils.Entities.Axis.Normal
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html#DynamoForRevitUtils_Entities_Axis_Normal
  name: Normal
  nameWithType: Axis.Normal
  fullName: DynamoForRevitUtils.Entities.Axis.Normal
- uid: DynamoForRevitUtils.Entities.Axis.IsPerpendicular*
  commentId: Overload:DynamoForRevitUtils.Entities.Axis.IsPerpendicular
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html#DynamoForRevitUtils_Entities_Axis_IsPerpendicular
  name: IsPerpendicular
  nameWithType: Axis.IsPerpendicular
  fullName: DynamoForRevitUtils.Entities.Axis.IsPerpendicular
- uid: DynamoForRevitUtils.Entities.Axis.IsTranslated*
  commentId: Overload:DynamoForRevitUtils.Entities.Axis.IsTranslated
  isExternal: true
  href: DynamoForRevitUtils.Entities.Axis.html#DynamoForRevitUtils_Entities_Axis_IsTranslated
  name: IsTranslated
  nameWithType: Axis.IsTranslated
  fullName: DynamoForRevitUtils.Entities.Axis.IsTranslated
